### ISSUE TITLE
Nouvelle source ? ECDC

### ISSUE THREAD

**Issue by Binnette** [opencovid19-fr/data#128]
Hello, j'ai remarqué que la majeure partie des données de Santé Publique France viennent de l'ECDC.
Je pense que ça faudrait le coup d'extraire leurs données. Qu'en pensez-vous ?

Quid de la licence de ces données ?
On pourrait les contacter directement afin d'obtenir un extract de leur data ?

@jdesboeufs: tu en penses quoi ?

Voici quelques pointeurs, avec d'immenses tableaux remplis de données:
- https://www.ecdc.europa.eu/en/geographical-distribution-2019-ncov-cases
- https://www.ecdc.europa.eu/en/cases-2019-ncov-eueea
- https://www.ecdc.europa.eu/en/novel-coronavirus-china
- https://qap.ecdc.europa.eu/public/extensions/COVID-19/COVID-19.html (cliquer sur les onglets)

**Comment by jdesboeufs** [comment]
Je pense que ce doit être l'inverse. Santé publique France qui remonte des données à l'OCDE.
Mais il n'est pas possible qu'on y trouve des données qui ne sont pas publiées par Santé publique France, voire des données qui viennent d'autres institutions.

**Comment by Binnette** [comment]
C'est très probable :+1: Par contre, les données Monde et Europe viennent de l'ECDC. Leurs données seraient peut-être plus faciles à extraire ?

![image](https://user-images.githubusercontent.com/6597721/77094391-b3fbd900-6a0c-11ea-9a0d-d2bd2ba02610.png)

**Comment by abdoulsn** [comment]
Visible la source c'est ECDC. faisons des recherche dessus.

**Comment by Aranud74** [comment]
Bonjour,

Je suis nouveau dans tout ceci, github etc... donc désolé si je n'ai pas les bonnes manières, mais je suis intéressé par les données autour de cette épidémie, donc je fouine un peu partout.

Pour information, l'ECDC fournit bien les données, un fichier excel tous les jours, mais pas forcément aligné avec les chiffres communiqués par les différents organismes santé des pays.
Je m'explique, pour la France, les chiffres indiqués pour le 21/03 sont en fait les chiffres fournis par Santé publique hier soir... l'Espagne pareil. il y a donc un décalage d'un jour sur ce que je vois.

le lien est ici:
https://www.ecdc.europa.eu/sites/default/files/documents/COVID-19-geographic-disbtribution-worldwide-2020-03-21.xlsx

**Comment by abdoulsn** [comment]
C'est une granularité mondiale.

**Comment by JiPiBi** [comment]
@Aranud74 ECDC explique qu'il extrait le matin entre 06:00 et 10:00  et la France Publie à .... en tous cas sur des chiffres figés à 14:00
