### ISSUE TITLE
"Recovered" dans data/dist/chiffres-cles.*

### ISSUE THREAD

**Issue by nfabbiane** [opencovid19-fr/data#129]
Est-ce que il y a la possibilité d'avoir aussi le guéri dans les fichiers récapitulatifs ?

Ceci permettrait de calculer les actifs et, donc, la pression actuelle sur la santé publique. 

Merci.

**Comment by JiPiBi** [comment]
Comme @ColinMaudry ne me donne pas le choix en fermant le 218  :-) , je proposais aussi d'ajouter les hospitalisés qd les données sont disponibles , cela permettrait de mieux comprendre le ratio rea/hospitalises

**Comment by Binnette** [comment]
Hello, je viens de rajouter `gueris` dans le CSV.
Cf. 185a68c806cb65655296c4c42f57ee61e19091db

Je ferme le ticket. Si besoin, vous pouvez le rouvrir.
