### ISSUE TITLE
double sources dans chiffres-cles.csv

### ISSUE THREAD

**Issue by nicho2** [opencovid19-fr/data#130]
dans le fichier https://github.com/opencovid19-fr/data/blob/master/dist/chiffres-cles.csv
on retrouve des lignes en "doublons" par ex :

![image](https://user-images.githubusercontent.com/11471811/77055473-3a92c500-69d1-11ea-8a5f-01bda85ab1b2.png)
on a le même jour la même région (avec un code région différent
pareil pour la bourgogne franche comté mais avec deux sources différentes
![image](https://user-images.githubusercontent.com/11471811/77055649-8b0a2280-69d1-11ea-96f3-1bb88ccc765b.png)

Du coup l'analyse n'est pas facile.

**Comment by Wawvi** [comment]
La maille_code de la région Auvergne Rhône Alpes provenant de l'ARS est erronée.
Pour les deux sources différents d'une même région, j'utilise personnellement la valeur la plus élevée (la différence de valeur entre les deux sources peut être du à l'heure de publication des données).

**Comment by jdesboeufs** [comment]
Nous listons les chiffres données par tous les organismes.
Il serait possible de proposer un fichier où on consolide les valeurs.

**Comment by ColinMaudry** [comment]
On a corrigé le code région pour Auvergne Rhône Alpes (ARS) le 4/03.
https://github.com/opencovid19-fr/data/blob/master/agences-regionales-sante/auvergne-rhone-alpes/2020-03-04.yaml#L7

L'approche de @Wawvi est je pense un bon équilibre.

@nicho2 as-tu les réponses que tu cherchais ? On peut fermer ?

**Comment by nicho2** [comment]
ok, on peut fermer
