### ISSUE TITLE
Code région erroné au sein des données ARS

### ISSUE THREAD

**Issue by claustres** [opencovid19-fr/data#134]
Les données de l'auvergne https://github.com/opencovid19-fr/data/tree/master/agences-regionales-sante/auvergne-rhone-alpes contiennent le même code (27) que celles de la bourgogne. Ceci peut poser des problèmes de croisement des données pour des outils se basant sur le code et non le nom de la région.

Le code région devrait être 84 pour l'auvergne.

**Comment by jdesboeufs** [comment]
Oui c'est une erreur.
Codes à corriger !

**Comment by Binnette** [comment]
Je prends à priori le bon code c'est 84. qqu'un confirme SVP ?

**Comment by Binnette** [comment]
@claustres : c'est corrigé dans eca22b2. Merci pour le signalement :+1:

Si vous souhaitez encore nous aider, un peu de lecture : https://github.com/opencovid19-fr/comment-contribuer

**Comment by claustres** [comment]
Nous contribuons déjà en essayant de produire des données cartographiques prêtes à l'emploi au niveau départemental/régional à partir des données ARS de ce dépôt => https://github.com/kalisio/covid-19. Un lien a déjà été ajouté dans la dépôt de contribution.

**Comment by claustres** [comment]
Le bug est de retour sur les données du 17 et 18 mars.
