### ISSUE TITLE
Saint Barthelemy  et  Saint-Barthélémy

### ISSUE THREAD

**Issue by JiPiBi** [opencovid19-fr/data#135]
Bonjour

Je viens par des chemins detournés (depuis le repo du JHU en regardant les repos d'un intervenant) d'arriver sur ce repo

J'essayais moi meme de recuperer les données de santé publique  france et localement je recupère les infos de réanimation hospitalisation de bourgogne franche comté sur un site local 

J'ai donc eu le meme doublon que vous pour Saint Barthelemy

**Comment by JiPiBi** [comment]
Je viens de comparer les données pour Bourgogne Franche Comté et il semblerait que mon site local donne plus d'infos , y compris sur les hospitalisés .   
Est ce que les données vous intéressent : saisie manuelle car noyées dans un article de type presse ?

**Comment by ColinMaudry** [comment]
Oui, merci d'ouvrir un autre issue pour la BFC, ça fait beaucoup de questions d'un coup :pray:

**Comment by Binnette** [comment]
Hello @JiPiBi, j'ai fait une grosse passe sur les typo hier matin. J'ai tracé ici #209 toute les typo que j'ai corrigé. Merci de ta vigilance :+1:
