### ISSUE TITLE
Interopérabilité avec coronadatascraper

### ISSUE THREAD

**Issue by claustres** [opencovid19-fr/data#147]
Sur le site https://coronadatascraper.com/ le mapping des données pour la France n'est pas correct. Le problème semble connu, cf. https://github.com/lazd/coronadatascraper/issues/102. En attente de leur retour pour améliorer.

**Comment by Binnette** [comment]
Bon du coup, si je comprends bien, il n'y a rien que l'on peut faire de notre côté. Je ferme le ticket.

@claustres N'hésites pas à le rouvrir si tu as des actions concrètes à nous proposer :wink:

**Comment by claustres** [comment]
Je propose de le laisser ouvert tant que ça ne fonctonne pas car si en l'état on ne peut pas grand chose, lorsqu'ils auront fait évoluer leur architecture il faudra certainement reprendre le scrapper.

**Comment by Binnette** [comment]
Dans ce cas, je te propose de la rouvrir quand on pourra vraiment faire qqchose de notre côté :+1: 
Merci d'avance :wink:

**Comment by claustres** [comment]
Juste pour information ils l'ont directement fixé eux-mêmes suite à mes recommandations donc ça fonctionne maintenant.
