### ISSUE TITLE
ARS Réunion

### ISSUE THREAD

**Issue by Eymiks** [opencovid19-fr/data#154]
Bonsoir, j'ai trouvé des [communiqué de presse de la Réunion ](https://www.lareunion.ars.sante.fr/communiques-de-presse-0) mais je ne sais pas comment faire pour ajouter un dossier.

**Comment by liszto** [comment]
Il faut un fichier dedans pour ajouter un dossier sur les repo de type git. ;)

**Comment by liszto** [comment]
Je peux continuer ou te laisser faire. Je viens de faire une pull request pour ajouter au moins le premier cas ici : #156

**Comment by liszto** [comment]
@Eymiks je te laisse clore l'issue ;)
