### ISSUE TITLE
[TO DO] SPF du 24/01 au 07/02 à compléter et à rectifier

### ISSUE THREAD

**Issue by Eymiks** [opencovid19-fr/data#160]
A cette [archive](https://web.archive.org/web/20200212192607/https://www.santepubliquefrance.fr/maladies-et-traumatismes/maladies-et-infections-respiratoires/infection-a-coronavirus/articles/epidemie-de-coronavirus-covid-19-au-depart-de-wuhan-chine) on trouve quelques infos sur la localisation des cas au tout début, ils seraient à ajouter aux fichiers SPF, ainsi cela éviterait d'avoir des cas à l'échelle nationale non indiqué sur la carte. 
On peut également remarquer que certaines données sont décalées d'1 jour par rapport aux infos de SPF.

**Comment by Xapitoun** [comment]
on peut avoir plusieurs url dans un même fichier ?

**Comment by Eymiks** [comment]
Pour l'instant, s'il y a plus d'une url il faut les ajouter en commentaire en bas du fichier. je crois que c'est en cours de changement.

**Comment by Xapitoun** [comment]
bon voila j’ai traité le bulletin et mis à jour les fichiers. Par contre, je les ai ajouté dans le mauvais PR #189. On peut pas les changer de PR ?

**Comment by Eymiks** [comment]
Je sais pas trop, à la limite change le nom de la PR.

**Comment by ColinMaudry** [comment]
Si j'ai bien compris, maintenant ça se joue dans la PR #189. Je ferme ici.
