### ISSUE TITLE
ARS PACA 17/03

### ISSUE THREAD

**Issue by pmaranin** [opencovid19-fr/data#161]
Le communique n'indique pas clairement la repartition des cas entre les departements

> 4 personnes testées positives au coronavirus COVID-19 sont décédées. Il s’agit de quatre personnes hospitalisées dans les Alpes-Maritimes, les Bouches-du-Rhône et le Vaucluse.

Cependant le fichier yaml les attribue specifiquement a chaque departement (1 pour le 06, 2 pour le 13, 1 pour le 83)

Cela pose un probleme de cintinuite avec le fichier du 18 qui n'annoce plus de deces par departement

**Comment by EtienneDavid** [comment]
Est ce qu'il y a moyen de récupérer les données au niveau départementale ? Je veux bien m'occuper du Vaucluse par exemple. Mais je ne comprends pas très bien qui sont les interlocuteurs ?

**Comment by pmaranin** [comment]
J'ai fait une PR avec les modifs
