### ISSUE TITLE
Nombre de décès en France le 18 Mars 2020

### ISSUE THREAD

**Issue by elkolotfi** [opencovid19-fr/data#162]
Bonjour,

Sur vos données (et l'archive le montre aussi) le nombre de décès en france est de 244 pour le jour du 18/03/2020. Or, sur toutes les autres sources, je retrouve que le nombre est de 264 pour ce jour ci.

Ceci, fausse le calcul du nombre de morts par jour entre le 18 et le 19 et donne 218 au lieu de 208 affiché un peu partout.

**Comment by liszto** [comment]
Cela ne viendrait-il pas du fait que certaines régions n'ont pas encore leur fichier du 18 mars renseignés ? 
Exemple : Ile de France s'arrête au 17/03 pour le moment

**Comment by JiPiBi** [comment]
Sur le site de sante publique , c'était clairement marqué 244
Les données prises en compte par worldometers qui sont sutement largement réutilisées viennent de cette source https://www.bfmtv.com/sante/direct-coronavirus-covid-19-confinement-quarantaine-france-attestation-sortie-travail-masques-chine-italie-espagne-epidemie/

J'ai réécouté Jerome Salomon et il dit bien 264 .....
https://twitter.com/BFMTV/status/1240342002052538374

**Comment by jdesboeufs** [comment]
Le chiffre de 264 a été donné par le Ministère des Solidarités et de la Santé.
https://github.com/opencovid19-fr/data/blob/master/ministere-sante/2020-03-18.yaml#L7

On ne saura jamais si l'orateur a mal lu ses fiches :)

Quoi qu'il en soit les deux valeurs sont dans les fichiers de sortie, chacun prioriser les sources de son choix comme il l'entends.
