### ISSUE TITLE
Données PACA: définition des descripteurs

### ISSUE THREAD

**Issue by gbrault** [opencovid19-fr/data#165]
Quelle est la définition exacte des données? Ou bien y-a-t-il des points manquants?
![COVID19-PACA](https://user-images.githubusercontent.com/7886676/77149247-71301480-6a91-11ea-9765-5eb247924c9e.png)
Sur cette image, on voit que le descripteur 'décès' n'est pas complet ou que la définition que j'en ai comprise n'est pas bonne.
Qu'en pensez-vous?

**Comment by gbrault** [comment]
Ce sont les données pour "Provence-Alpes-Côte d’Azur"

**Comment by gbrault** [comment]
[Open_Covid_19.zip](https://github.com/opencovid19-fr/data/files/4358665/Open_Covid_19.zip)

Ceci est le notebook jupyter de traitement des données.

**Comment by gbrault** [comment]
Et... Merci pour votre initiative!

**Comment by pmaranin** [comment]
D'apres le fichier yaml il devrait y avoir [4 deces le 17](https://github.com/opencovid19-fr/data/blob/master/agences-regionales-sante/provence-alpes-cote-dazur/2020-03-17.yaml) mais effectivement ils ne sont pas dans le CSV

**Comment by gbrault** [comment]
et la même chose pour le 19 [yaml](https://github.com/opencovid19-fr/data/blob/3f25f93660fc222c34f1ed0e184e61fa4604990e/agences-regionales-sante/provence-alpes-cote-dazur/2020-03-19.yaml#L13)

**Comment by gbrault** [comment]
![image](https://user-images.githubusercontent.com/7886676/77152710-c1f73b80-6a98-11ea-8b98-657daff0a316.png)

Les données du 17, 18 et 19 sont en double le 11 aussi il y en a plein comme ça... Est-ce volontaire et donc je dois faire un filtre supplémentaire ou bien un 'bug'?

**Comment by pmaranin** [comment]
c;est parce que pour ces dates il ya une entree SPF et une entree ARS

**Comment by gbrault** [comment]
Ok, donc je filtre sur ARS
![image](https://user-images.githubusercontent.com/7886676/77156753-4f8a5980-6aa0-11ea-99ec-2d271e47a65d.png)

**Comment by gbrault** [comment]
Voici le nouveau notebook 
[Open_Covid_19.zip](https://github.com/opencovid19-fr/data/files/4359073/Open_Covid_19.zip)

**Comment by gbrault** [comment]
Merci!
