### ISSUE TITLE
[QUESTION] Comment rentrer certaines données dans nos fichiers ?

### ISSUE THREAD

**Issue by liszto** [opencovid19-fr/data#17]
Concernant la Nouvelle Aquitaine, les les chiffres sont rectifiés d'un communiqué à l'autre.
Comment soumettre les valeurs dans ces cas là ?

Dans le cas ou un cas passe d'un jour en confirmé en négatif le lendemain via un Erratum, comment le rentrer dans nos datas ?

**Comment by jdesboeufs** [comment]
Excellente question.
Vous avez un communiqué qui peut servir d'exemple ?

**Comment by liszto** [comment]
Oui celui-ci pour l'erratum concernant le passage en négatif après tests supplémentaires : 
https://www.nouvelle-aquitaine.ars.sante.fr/communique-de-presse-coronavirus-point-de-situation-en-nouvelle-aquitaine-du-06032020
Ce que j'avais fait dans mes fichiers (non soumis pour le moment) est la chose suivante :
```
  casConfirmes: 72
  casNegatifs: 1
  gueris: 1
  reanimation: 0
  deces: 0
```
J'ai rajouté une entrée cas négatifs mais ca fait faire une gymnastique en supprimant une entrée dans les positifs. De leur côté dans le décompte il ne le retire pas (à priori). Donc il serait envisageable de les laisser comme eux (même si je trouve que cela biaise les données recueilli étant donné que le cas invalidé ne ressort nul par en suite).

Pour les chiffres qui varient entre 2 rapports (et parfois sans raison logique, les voici) : 
https://www.nouvelle-aquitaine.ars.sante.fr/communique-de-presse-coronavirus-point-de-situation-en-nouvelle-aquitaine-du-09032020
et 
https://www.nouvelle-aquitaine.ars.sante.fr/communique-de-presse-coronavirus-point-de-situation-en-nouvelle-aquitaine-du-11032020
On peut voir que le 09/3 on est à 39 et que le 10/03 on serait à 72 en rajoutant seulement 17cas. 🤔 
De plus ils précisent que dans leur décompte de midi 2 des 17 cas n'était pas en réalité testés positifs. Mais le sont-ils dans ce communiqué, je ne sais pas trop.

De plus pour cette région, les formats changent parfois. On a également eu droit à un tableau en date du 08/03
