### ISSUE TITLE
Insertion des données #casRéa du point video Ministère Santé

### ISSUE THREAD

**Issue by cecilaki** [opencovid19-fr/data#176]
Je m'en suis occupée et j'ai relevé avec @scrouzet les données relatives aux cas en réanimation (principalement) des vidéos aux dates : 

- 4 mars
- 5 mars
- 6 mars
- 9 mars
- 10 mars
- 11 mars
- 14 mars
- 17 mars
- 18 mars
- 19 mars

Pas de point Min. Santé aux dates manquantes (15/16 mars+ 12/13 mars), ou pas de vidéo trouvée sur ce canal (Dailymotion)

**Comment by scrouzet** [comment]
Je viens d'ajouter le 3 mars. Je confirme que pour les jours manquants dans les relevés pushés sur le git par cecilaki, les vidéos n'existent pas sur dailymotion.

**Comment by Kuzcoo** [comment]
Gros boulot, bravo 👍

**Comment by ColinMaudry** [comment]
Du coup c'est fait ?

**Comment by cecilaki** [comment]
Oui tu peux

**Comment by ColinMaudry** [comment]
Merci, ça permet de voir plus claire dans les issues :pray:
