### ISSUE TITLE
Beaucoup de liens d'archive ne marchent pas

### ISSUE THREAD

**Issue by abdoulsn** [opencovid19-fr/data#190]
Dois t-on continuer à alimenter cette balise, j'ai testé au random des lien mais sans résultats.

**Comment by tiphaine** [comment]
Hello @abdoulsn, est ce que tu peux donner des exemples pour qu'on reproduise ou que ce soit corrigé ?

**Comment by abdoulsn** [comment]
C'était ma connexion ou un problème avec le site, quand je testais les liens il charge la page et restait en noire.
Il marche bien, avec mon téléphone.
