### ISSUE TITLE
incohérence de data

### ISSUE THREAD

**Issue by abdoulsn** [opencovid19-fr/data#192]
Les données que j'ai trouvé [ici](https://github.com/opencovid19-fr/data/blob/master/sante-publique-france/2020-03-15.yaml) ne sont pas en accord avec le pdf du date 2020-03-15 disponible [ici]( https://www.santepubliquefrance.fr/maladies-et-traumatismes/maladies-et-infections-respiratoires/infection-a-coronavirus/documents/bulletin-national/covid-19-point-epidemiologique-du-15-mars-2020)  toutes étant issue de SPF.

**Comment by Kuzcoo** [comment]
@abdoulsn : ce sont les données consolidées arrêtées à minuit. Si tu regardes l'archive sur le fichier que tu mentionner (yml) tu peux voir la version "figée" à 15h qui est correct. Ceci dit celà vaudrait sûrement le coup de mettre à jour le yml avec ces données consolidées. Il y a des chiffres complémentaires qui plus est.

**Comment by abdoulsn** [comment]
Ok d'accord mais c'est cas même un peut bizare, IDF sur le yml est a ~1200 et le pdf est a ~1840, d'ou vient cette grande différence alors.

**Comment by tberriot** [comment]
doublon d'issue avec #148

**Comment by abdoulsn** [comment]
> doublon d'issue avec #148

sure, j'ai manqué cette issue.
