### ISSUE TITLE
Interet de maintenir la granularite collectivite-outremer ?

### ISSUE THREAD

**Issue by JiPiBi** [opencovid19-fr/data#216]
SVP Pourquoi traitez vous les territoires outre mer à un niveau spécifique : santé publique les traite comme des régions et de votre coté vous avez une double gestion : Martinique /Guadeloupe  ... comme région  comme une region de métropole  et Saint Barthelemy Saint Martin  comme Collectivité d'outre-mer 
N'y aurait il pas un interet à simplifier en supprimant un niveau et s'aligner sur les critères de santé publique ?

**Comment by jdesboeufs** [comment]
Santé publique France se base sur son organisation administrative.
Ils ont "autorité" sur Saint-Barthelemy et Saint-Martin car auparavant c'était des communes de la Guadeloupe.

Il n'empêche qu'en 2020, Saint Martin, Saint Barthelemy, Saint-Pierre-et-Miquelon, la Polysénie… sont des collectivités d'outre-mer, avec un registre de codes particuliers.

**Comment by JiPiBi** [comment]
Qui serais je pour remettre  en cause les decoupages adminsitratifs  francais :-)
Non je parlais juste de la facilité d'emploi de la base de données , c'est d'ailleurs aussi une subtilité qui a échappé au site CSSE .

**Comment by ColinMaudry** [comment]
@JiPiBi À moins qu'il reste des choses à éclaircir, peux-tu fermer l'issue ?

**Comment by JiPiBi** [comment]
Donc je comprends que vous ne souhaitez pas changer , dont acte , mais SVP dans ce cas expliquez quelque part comment utiliser vos données par exemple dans le READ.ME  (sauf si j'avais mal lu ou mal parcouru votre repo  :- ) ) 
Merci d'avance
