### ISSUE TITLE
[TO DO] ARS Mayotte : Données à retranscrire

### ISSUE THREAD

**Issue by Eymiks** [opencovid19-fr/data#217]
Bonjour, l'ARS de Mayotte publie des communiqués régulièrement, il faudrait les ajouter.
https://www.mayotte.ars.sante.fr/liste-communiques-presse

**Comment by liszto** [comment]
@Eymiks je commence à regarder ça de suite :)

**Comment by Eymiks** [comment]
Ok, je te remercie.

**Comment by liszto** [comment]
Voilà la PR associée : #220

**Comment by Eymiks** [comment]
Ok je ferme.
