### ISSUE TITLE
Hospitalisés manquants dans le CSV

### ISSUE THREAD

**Issue by JiPiBi** [opencovid19-fr/data#218]
Bonjour 
Dans les données Santé Publique et ARS on a parfois le nombre de personnes hospitalisées et de guéris , meme si ce n'est pas tous les jours et vos fichiers yaml en font bien mention
Ce type de données est aussi disponible sur le site italien au niveau regional , mais pas provincial ou ils ne traitent seulement que les cas confirmés 
http://opendatadpc.maps.arcgis.com/apps/opsdashboard/index.html#/b0c68bce2cce478eaac82fe38d4138b1

SVP pourquoi ne reportez vous pas ces données dans les fichiers csv ?

Edit : je viens de voir qu'il y a un autre issue sur les guéris

**Comment by ColinMaudry** [comment]
Oui c'est #129. Du coup je ferme ;)

**Comment by JiPiBi** [comment]
@ColinMaudry pas tout a fait d'accord pour fermer brutalement sans comprendre la suite 
Il reste les hospitalisés 
Éventuellement,  je peux rajouter un commentaire dans le 129

**Comment by ColinMaudry** [comment]
Je pense qu'il vaut mieux renommer cet issue en ne laissant dans le titre que les hospitalisés.

**Comment by Binnette** [comment]
Hello, je viens de corrigé nos scripts.

Les chiffres 'hospitalises' sont maintenant dispo dans le CSV
Cf. 52c1611733345bb829a8c75e0dedf70f3f962559

Je ferme le ticket. Si besoin, vous pouvez le rouvrir.

**Comment by JiPiBi** [comment]
Entendu, merci beaucoup  j'ai modifié mes scripts , ca marche , du coup on voit tous les manques , je vais analyser en commençant par BFC
