### ISSUE TITLE
Donnees incoherentes

### ISSUE THREAD

**Issue by JiPiBi** [opencovid19-fr/data#222]
Le sujet est peut etre connu 
En essayant de tracer  des courbes au niveau regional , j'ai utilisé la valeur max s'il y avait 2 valeurs pour la meme date suivant 2 sources , mais j'en arrive hélas à des incoherences 

07/03/2020 | region | REG-27 | Bourgogne-Franche-ComtÃ© | 106 | 0 |   | ARS Bourgogne-Franche-ComtÃ©
-- | -- | -- | -- | -- | -- | -- | --
07/03/2020 | region | REG-27 | Bourgogne-Franche-ComtÃ© | 129 |   |   | SantÃ© publique France
08/03/2020 | region | REG-27 | Bourgogne-Franche-ComtÃ© | 112 | 0 |   | ARS Bourgogne-Franche-ComtÃ©
09/03/2020 | region | REG-27 | Bourgogne-Franche-ComtÃ© | 119 | 0 |   | ARS Bourgogne-Franche-ComtÃ©

![index](https://user-images.githubusercontent.com/44967630/77233798-2524c300-6baa-11ea-92d2-8bc47ed8220c.png)

SVP est ce que vous pouvez me proposer une solution pour ma gestion des données ?
(probleme similaire en Ile de France pour les 14 15 mars)

**Comment by ColinMaudry** [comment]
Si ce n'est pas pas fait, vous pourriez rajouter les données ARS pour le 7 mars, et vous limiter à une même source pour chaque région.

**Comment by JiPiBi** [comment]
OK mais à votre avis laquelle est la plus fiable : ARS ?

**Comment by jcavfen9** [comment]
> OK mais à votre avis laquelle est la plus fiable : ARS ?

Dans le doute, j'ai fait une moyenne? De toute façon les données départements/régions ne sont déjà pas cohérentes du fait des différents rythmes de mises à jour donc pour [la représentation graphique ....](https://public.tableau.com/shared/38YGTQ48Q?:display_count=y&:origin=viz_share_link) :-)

**Comment by JiPiBi** [comment]
J'ai fait un test en n'utilisant que les données ARS , mais le pb est que les cas confirmés sont plutôt donnés par Sante Publique , surtout ces derniers jours 

Donc pour le niveau régional, je vais prendre la valeur sante-publique pour les confirmés  et pour les autres indicateurs la valeur ARS
Mais  les valeurs confirmés  sante publique sont incomplètes en début de courbe .....

![image](https://user-images.githubusercontent.com/44967630/77259636-24139480-6c83-11ea-8852-5d5c66f4b4c9.png)

Personnellement prendre la valeur moyenne quand 2 valeurs sont differentes ne me convient  pas,surtout quand on pense qu'il y en a une des 2 qui peut être due à une erreur (exemple du 244 - 264 entre Jerome Salomon et le site Sante Publique) 

Plus généralement, sauf si vous l'aviez déjà fait , je pourrais regarder pour une date et une entité donnée s'il existe d'autres incohérences entre les sources 

Je clos donc cette issue
