### ISSUE TITLE
Donnees officielles Grand Est du 21/ 03 par sante publique semblent trop optimistes 

### ISSUE THREAD

**Issue by JiPiBi** [opencovid19-fr/data#225]
Bonjour 
je vois sur le site Sante publique une valeur de 3089, soit +83 par rapport à la veille ce qui me semble incoherent 

![image](https://user-images.githubusercontent.com/44967630/77234752-3fae6a80-6bb1-11ea-8fff-ffe24053f8a1.png)

**Comment by Eymiks** [comment]
On va attendre le communiqué de l'ARS pour voir s'il y a une incohérence ou pas.

**Comment by ColinMaudry** [comment]
Le communiqué de l'ARS pour le 21/03 : https://www.grand-est.ars.sante.fr/system/files/2020-03/Communique%20Coronavirus%20covid%2019%20-%20point%20de%20situation%20en%20Grand%20Est%2021%2003%202020.pdf

**Comment by ColinMaudry** [comment]
Le communiqué l'indique assez clairement : ils comptent les personnes hospitalisées. 

@JiPiBi peux-tu nous donner l'URL de ton graphique ? Vu l'échelle de valeur, on peut sans trop de risque supposer que le graphique cherche à illustrer le nombre de cas confirmés, et pas le nombre de personnes hospitalisées.

Mais ils ont pris les chiffres Grand Est sans regarder de plus près...

**Comment by JiPiBi** [comment]
C'est un graphique personnel bases sur les donnéés journalieres de sante publique que je copie colle dans un fichier EXCEL , ce sont les memes valeurs que vous . J'ai juste vu cette bizarre inflexion .
Si l'ARS ne communique plus , il y a qqun à sante publique qui a calculé le chiffre de 3089  , à mon avis basé sur l'écart en réanimés qui est le meme chiffre d'ou la confusion

**Comment by JiPiBi** [comment]
Pour info worldometers a une ligne France qui prend le total France + territoires et continue à avoir des ligne par territoire , comptées donc en double , j'ai remonté 2fois  le pb mais pas de réactions pour le moment

**Comment by JiPiBi** [comment]
En tous cas , il faudrait peut etre indiquer quelque part que le 3089 n'est pas fiable ?

**Comment by ColinMaudry** [comment]
Je pense que dans ce cas il faut répertorier la donnée de l'ARS pour avoir au moins une bonne donnée grand est pour cette date. Peux-tu le faire ?

**Comment by ColinMaudry** [comment]
Tu peux aussi, dans ta PR, commenter sous cette ligne pour indiquer qu'elle ne décompte que les hospitalisés et pas tous les cas confirmés ? https://github.com/opencovid19-fr/data/blob/master/sante-publique-france/2020-03-21.yaml#L29

**Comment by Binnette** [comment]
Les données ont été corrigées dans #241 et je viens de regénérer le CSV et le JSON dans 249baaa1d970704ef1c0febcbacb48a36678754b

Merci de fermer le ticket si tout est OK.

**Comment by JiPiBi** [comment]
Je n'ai pas bien compris ce que vous attendiez de moi , je ne suis pas un expert github et je ne voudrais pas tout vous casser : je sais faire un fetch merge   depuis mon PC  ou un push sur mes repos dans les 2 sens , mais en collaboratif je n'ai pas d'experience 
De plus  je n'ai pas compris sur quels fichiers vous voudriez que je travaille (yaml de ARS ? ) et comment le faire (creer un fork ?)  . désolé ....;

Pour Grand-Est avec les valeurs de votre site , la courbe devient

![image](https://user-images.githubusercontent.com/44967630/77260320-6343e480-6c87-11ea-9e45-48930b940d56.png)

**Comment by Binnette** [comment]
@JiPiBi : Non, je voulais juste que tu me confirmes que les données était corrigées dans le CSV :wink:

**Comment by JiPiBi** [comment]
Comme je le disais la courbe est issue de vos données.
Le 3089 est le chiffre Sante Publique 
Il n y a pas de chiffre ARS
Ni le yaml de Sante Publique, ni le yaml de ARS ne font mention du fait que cette donnée est peut-être une anomalie. Je vais vérifier si par hasard pour le 22 ce n'est pas la même chose, cad ajout d'un delta de réa ou d hospitalises au lieu de cas.

**Comment by Binnette** [comment]
Si tu vois des erreurs entre les fichiers YAML et les source (bulletins des ARS, SPF, etc), n'hésites pas à créer des issues.

**Comment by JiPiBi** [comment]
Comptez sur moi , mais je sais aussi que comme toute saisie manuelle , il y a des risques d'erreur , sans aucun jugement de valeur sur la qualité des gens qui ont fait la saisie, c'est inhérent à la saisie manuelle (sauf qd sur un site comme celui du  CSSE les remontées d'erreur ne sont pas traitées , où l'énervement et le doute règnent)

Vous faites un travail enorme de compilation dont on vous remercie , qui dans un pays comme l'Italie est fait par la protection civile  qui met immediatement à disposition ses données. 
Vous devez connaitre ce site très bien fait : https://github.com/pcm-dpc/COVID-19 qui les récupère et que j'utilise . Ce site est sourcé par worldometers
