### ISSUE TITLE
Completude variable des données regionales 

### ISSUE THREAD

**Issue by JiPiBi** [opencovid19-fr/data#239]
Bonjour 

En regardant les valeurs de Rea et de Deces au niveau région , les regions sont inegalement renseignées : BFC assez complet , IDF pas très rempli

Je n'ai pas regardé dans vos fichiers yaml , mais y a t il une raison ?

**Comment by chamtec** [comment]
Bonjour,
Cela dépend des données fournies par les ARS.
C'est dommage de ne pas avoir les même données pour chacune des régions.

**Comment by ColinMaudry** [comment]
Effectivement, nous dépendons de ce que fournissent les sources. Pour une même ARS ça peut varier d'un jour à l'autre. Vous pouvez vérfier en comparant les données avec la source.
