### ISSUE TITLE
Information sur un tableau de bord realisé sur la base du dataset CSSE

### ISSUE THREAD

**Issue by JiPiBi** [opencovid19-fr/data#261]
Je ne sais pas si vous connaissez l'outil datastudio de google , mais dans une issue quelqu'un a montré ses possibilités :
https://datastudio.google.com/u/0/reporting/9ce371f1-62fa-4f2e-8d3c-da4d6dff967b/page/znKJB

Peut inspirer des idées

**Comment by jcavfen9** [comment]
> Peut inspirer des idées

[Le lien vers le dashboard que j'ai réalisé avec Tableau Software](https://public.tableau.com/views/Coronavirus2019-nCoVstats/Coronavirus2019-nCoV?:retry=yes&:display_count=y&:origin=viz_share_link). L'intérêt est la possibilité de "blender" des données. J'ai pu réaliser une carte avec le ratio pour 100.000 (4ème onglet). Intéressant de découvrir que ce ratio est presque double en Norvège par rapport à la France.

**Comment by JiPiBi** [comment]
@jcavfen9 
Je vois que vous n'avez pas attendu pour etre inspiré !
C'est très impressionnant 
Je suis comme vous je pense qu'on manque de données sur la situation des hopitaux , mais je pense sans etre complotiste que ce sont des données trop sensibles pour etre mises dans le domaine public

Par contre , en me répétant par rapport à ce que j'ai écrit dans un autre lien , c'est anormal que la France ne communique pas ses données au même niveau que celui fourni par l'Italie et que des gens galèrent ici pour les saisir manuellement

**Comment by Binnette** [comment]
@JiPiBi Merci pour le partage, ici nous bossons uniquement sur les données :wink: 
Mais si tu as des axes d'améliorations concrets pour le dashboard, ça se passe ici :wink: 
https://github.com/opencovid19-fr/dashboard/issues

**Comment by jcavfen9** [comment]
> Par contre , en me répétant par rapport à ce que j'ai écrit dans un autre lien , c'est anormal que la France ne communique pas ses données au même niveau que celui fourni par l'Italie et que des gens galèrent ici pour les saisir manuellement

Entièrement d'accord avec vous. Je vais essayer de laisser un mot gentil sur le [LinkedIn du gars](https://www.linkedin.com/feed/update/urn:li:activity:6646000599789907968/). Je réfléchis à comment le tourner pour qu'il soit constructif.

**Comment by JiPiBi** [comment]
@Binnette  
oups , je ne connaissais pas le lien git dashboard , je vais regarder si je peux accéder à vos analyses

**Comment by JiPiBi** [comment]
@jcavfen9 
tant pis si je me fais tapper sur les doigts  : dans l'onglet crude rates la population de la France serait de 328 000 000, pour Netherland aussi , donc il faut verifier votre table de population
Y a t il un autre moyen de vous faire des retours ?

**Comment by Binnette** [comment]
@jcavfen9, @JiPiBi : rejoignez-vous sur Slack, vous pourrez vous envoyer des messages privés.
https://join.slack.com/t/dataagainstcovid-19/shared_invite/zt-cgsplso2-LIvWeRHlf1ZFIrh~SPj~IA

**Comment by jcavfen9** [comment]
> rejoignez-vous sur Slack, vous pourrez vous envoyer des messages privés.

C'est fait. A bientôt.

**Comment by jcavfen9** [comment]
> tant pis si je me fais tapper sur les doigts : dans l'onglet crude rates la population de la France serait de 328 000 000, pour Netherland aussi j'ai vu des chiffres forts , donc il faut verifier votre table de population

Au contraire 👍 
Grosse erreur de ma part 👎, je vais essayer de corriger ça. ASAP.

> Y a t il un autre moyen de vous faire des retours ?

J'ai rejoins le groupe Slack proposé par Binnette .... il y a du niveau !

**Comment by JiPiBi** [comment]
@jcavfen9 
Je n'ai pas réussi  à recevoir le fameux mail 
En meme temps s'il y a du niveau , peut etre que c'est normal  qu'ils ne m'acceptent pas  :-(

**Comment by jcavfen9** [comment]
> Je n'ai pas réussi à recevoir le fameux mail
> En même temps s'il y a du niveau , peut-être que c'est normal qu'ils ne m'acceptent pas :-(

Je crois que c'est ouvert à tout le monde. Il faut vous inscrire sur Slack puis https://dataagainstcovid-19.slack.com 

J'ai corrigé et mis à jour mon dashboard. Ce fut compliqué car JHU à encore changé le format 👎

**Comment by JiPiBi** [comment]
@jcavfen9 
je vien enfin de réussir à me connecter à Slack,  sous le meme nom JiPiBi 
Comme je ne connais pas votre identifiant Slack , vous pouvez essayer SVP de me contater 

Pour les données JHU , je propose d'en discuter sous Slack , je ne comprends pas tout ce qu'ils ont fait pour les recovered (dans les daily , plus dans les times series ?)
J'ai aussi changé un peu d'avis sur Geodes , je n'avais pas tout vu
