### ISSUE TITLE
Données PACA à vérifier et à intégrer

### ISSUE THREAD

**Issue by Binnette** [opencovid19-fr/data#273]
Erreur rapportée par "D. Gisclon" sur https://www.data.gouv.fr/fr/organizations/opencovid19-fr/
Il va falloir passer en revue les chiffres PACA qui à priori ne sont pas corrects.

Des volontaires ?

**Edit :** à priori, on a déjà tous les fichiers sauf le 22, mais "D Gisclon" semble dire qu'il y a des erreurs. 

----

⚠️ Merci de ne pas copier/coller ces données dans les fichiers YAML, il convient de tout revérifier en lisant les bulletins et communiqués de presse

💡 La source principale est l'ARS PACA, donc les fichiers sont à mettre dans le répertoire [agences-regionales-sante/provence-alpes-cote-dazur](https://github.com/opencovid19-fr/data/tree/master/agences-regionales-sante/provence-alpes-cote-dazur)

⚠️ Merci de faire **une** Pull Request par fichier afin que l'intégration soit plus rapide

💡 Si vous voulez vous occuper d'un des fichiers, merci de réagir avec l’icône `:rocket:` sur le message concerné 🚀 

----

:boom: 
* le lien du "Point de situation au 19 mars" ne fonctionne pas
* le lien du "Point de situation du 22 mars" n'est pas indiqué

**Comment by Binnette** [comment]
Message de "D. Gisclon"

Je vois qu’il vous manque les chiffres pour la région PACA du 2203
Récupéré de Ars
https://m.facebook.com/story.php?story_fbid=3163580943675065&id=122014131165110
Point de situation du 22 mars :
1316 personnes testées positives #Covid19 en #Paca

🔘22 dans les Alpes-de-Haute-Provence
🔘 42 personnes dans les Hautes-Alpes ;
🔘194 personnes dans les Alpes-Maritimes ;
🔘827 personnes dans les Bouches-du-Rhône ;
🔘186 personnes dans le Var ;
🔘45 personnes dans le Vaucluse.

Parmi elles :
⚫️85 personnes en réanimation ;
⚫️15 personnes décédées.

**Comment by Binnette** [comment]
Message de "D. Gisclon"

En remontant voici tous chiffres que j’ai pu vous trouver pour compléter la région paca
Via tjrs Ars

ℹ️#Coronavirus #Covid19 Communiqué de presse : point de situation du 4 mars 2020.

18 cas confirmés en région #Paca
🔘10 personnes dans les Alpes-Maritimes
🔘7 personnes dans les Bouches-du-Rhône
🔘1 personne dans le Vaucluse

👉https://www.paca.ars.sante.fr/coronavirus-en-provence-alpes-cote-dazur-point-de-situation

**Comment by Binnette** [comment]
Message de "D. Gisclon"

#Coronavirus #Covid19 en Paca : point de situation du 5 mars ℹ️
26 cas confirmés en région #Paca :
🔘14 personnes dans les Alpes-Maritimes ;
🔘7 personnes dans les Bouches-du-Rhône ;
🔘3 personnes dans les Hautes-Alpes ;
🔘1 personne dans le Var ;
🔘1 personne dans le Vaucluse.
👉https://www.paca.ars.sante.fr/coronavirus-en-provence-alpes-cote-dazur-point-de-situation-0
Ministère des solidarités et de la santé

Xxx 6?
Xxx 7?
Xxx 8?
Xxx 9?

**Comment by Binnette** [comment]
Message de "D. Gisclon"

#Covid19 Point de situation 10 mars
90 cas confirmés #Paca
🔘2 dans les Alpes-de-Haute-Provence
🔘14 dans les Hautes-Alpes
🔘23 dans les Alpes-Maritimes
🔘37 dans les Bouches-du-Rhône
🔘11 dans le Var
🔘3 dans le Vaucluse
https://www.paca.ars.sante.fr/coronavirus-en-provence-alpes-cote-dazur-point-de-situation-du-10-mars

Xxx 11?

**Comment by Binnette** [comment]
Message de "D. Gisclon"

#Covid19 Point de situation au 12 mars
151 cas confirmés #Paca
🔘4 dans les Alpes-de-Haute-Provence
🔘15 dans les Hautes-Alpes
🔘39 dans les Alpes-Maritimes
🔘67 dans les Bouches-du-Rhône
🔘22 dans le Var
🔘4 dans le Vaucluse
➡https://www.paca.ars.sante.fr/coronavirus-en-provence-alpes-cote-dazur-point-de-situation-du-12-mars

**Comment by Binnette** [comment]
Message de "D. Gisclon"

#Covid19 Point de situation au 13 mars
211 cas confirmés #Paca
🔘4 dans les Alpes-de-Haute-Provence
🔘18 dans les Hautes-Alpes
🔘43 dans les Alpes-Maritimes
🔘93 dans les Bouches-du-Rhône
🔘48 dans le Var
🔘5 dans le Vaucluse
➡️https://www.paca.ars.sante.fr/coronavirus-en-provence-alpes-cote-dazur-point-de-situation-au-13-mars

Xxx 14?
Xxx 15?
Xxx 16?

**Comment by Binnette** [comment]
Message de "D. Gisclon"

#Covid19 Point de situation au 17 mars
481 cas confirmés #Paca
🔘7 dans les Alpes-de-Haute-Provence
🔘25 dans les Hautes-Alpes
🔘104 dans les Alpes-Maritimes
🔘237 dans les Bouches-du-Rhône
🔘95 dans le Var
🔘13 dans le Vaucluse
➡ ttps://www.paca.ars.sante.fr/coronavirus-en-provence-alpes-cote-dazur-point-de-situation-au-17-mars

**Comment by Binnette** [comment]
Message de "D. Gisclon"

#Covid19 Point de situation au 18 mars
566 cas confirmés #Paca
🔘7 dans les Alpes-de-Haute-Provence
🔘32 dans les Hautes-Alpes
🔘110 dans les Alpes-Maritimes
🔘303 dans les Bouches-du-Rhône
🔘103 dans le Var
🔘15 dans le Vaucluse
➡️ https://www.paca.ars.sante.fr/coronavirus-en-provence-alpes-cote-dazur-point-de-situation-au-18-mars

**Comment by Binnette** [comment]
Message de "D. Gisclon"

#Covid19 Point de situation au 19 mars
690 cas confirmés #Paca
🔘8 dans les Alpes-de-Haute-Provence
🔘31 dans les Hautes-Alpes
🔘133 dans les Alpes-Maritimes
🔘377 dans les Bouches-du-Rhône
🔘124 dans le Var
🔘17 dans le Vaucluse
➡️ https://www.paca.ars.sante.fr/coronavirus-en-provence-alpes…

**Comment by Binnette** [comment]
Message de "D. Gisclon"

Point de situation au 20 mars :
755 personnes testées positives #Covid19 en #Paca
🔘15 dans les Alpes-de-Haute-Provence
🔘34 dans les Hautes-Alpes
🔘142 dans les Alpes-Maritimes
🔘408 dans les Bouches-du-Rhône
🔘132 dans le Var
🔘24 dans le Vaucluse
Parmi ces cas
⚫44 personnes en réanimation ;
⚫9 personnes sont décédées.
➡https://www.paca.ars.sante.fr/coronavirus-en-paca-point-de-situation-du-20-mars-2020

**Comment by Binnette** [comment]
Message de "D. Gisclon"

Point de situation du 21 mars :
1041 personnes testées positives #Covid19 en #Paca
🔘17 dans les Alpes-de-Haute-Provence
🔘 35 personnes dans les Hautes-Alpes ;
🔘174 personnes dans les Alpes-Maritimes ;
🔘572 personnes dans les Bouches-du-Rhône ;
🔘159 personnes dans le Var ;
🔘32 personnes dans le Vaucluse.
Parmi elles :
⚫️75 personnes en réanimation ;
⚫️13 personnes décédées.

https://www.paca.ars.sante.fr/coronavirus-point-de-situation-du-21-mars-2020

**Comment by Binnette** [comment]
Message de "D. Gisclon"

Point de situation du 22 mars :
1316 personnes testées positives #Covid19 en #Paca
🔘22 dans les Alpes-de-Haute-Provence
🔘 42 personnes dans les Hautes-Alpes ;
🔘194 personnes dans les Alpes-Maritimes ;
🔘827 personnes dans les Bouches-du-Rhône ;
🔘186 personnes dans le Var ;
🔘45 personnes dans le Vaucluse.
Parmi elles :
⚫️85 personnes en réanimation ;
⚫️15 personnes décédées.

**Comment by abdoulsn** [comment]
dans que repo doit on le faire @Binnette

**Comment by Binnette** [comment]
Hello, ça dépends des sources. Mais à priori, la source principale c'est l'ARS PACA.
ça sera donc ici : https://github.com/opencovid19-fr/data/tree/master/agences-regionales-sante/provence-alpes-cote-dazur

**Comment by antoan2** [comment]
La PR pour le 22 mars: https://github.com/opencovid19-fr/data/pull/277

Je m'occupe des autres commentaires en début d'aprem sauf si @abdoulsn tu as déjà commencé à travailler dessus.

**Comment by abdoulsn** [comment]
> La PR pour le 22 mars: #277
> 
> Je m'occupe des autres commentaires en début d'aprem sauf si @abdoulsn tu as déjà commencé à travailler dessus.

tout le monde est motivé, tout est en cours apparemment. Merci à tous

**Comment by antoan2** [comment]
Je n'ai pas trouvé les erreurs dont parle "D. Gisclon", les chiffres sont les mêmes que dans les rapports.

Sinon il manque les données pour le 14, 15, et 16 mars.

Je ne comprends pas bien comment d'où ce journaliste a récupéré les données : https://france3-regions.francetvinfo.fr/provence-alpes-cote-d-azur/coronavirus-france-compte-4500-cas-confirmes-passe-au-stade-3-1800058.html

**Comment by Binnette** [comment]
Merci @antoan2 d'avoir tout vérifié. :+1: 

Pour les données des 14, 15, 16, j'ai bêtement demandé à mon moteur de recherche préféré.

A écouter pour voir s'il y a de la data:
- https://www.dailymotion.com/video/x7sqj0i
- https://www.dailymotion.com/video/x7slb2x
- https://www.dailymotion.com/video/x7sg2a4

Autres vidéos ? https://www.dailymotion.com/gouvernementFR/videos

**Comment by abdoulsn** [comment]
je m'en charge demain à la pause 12h, si y a personne entre temps.
