### ISSUE TITLE
Données BFC manquantes  pour 21 22 Mars

### ISSUE THREAD

**Issue by JiPiBi** [opencovid19-fr/data#275]
Bonjour 
Je vois que vos yaml pour les 21 22 ne sont pas encore créés 

J'ai 2 methodes pour charger les fichiers ARS BFC  , soit par une interro directe avec un script du site ARS
Soit en utilisant vos yaml 

Comme les yaml n'existent pas pour ces dates , c'est la première methode que j'utilise , mais il n'arrive pas à charger le 21 (j'ai revérifié il charge tout depuis le debut du mois jusqu'au 22 sauf le 21)

Je n'arrive pas à trouver sur le site ARS BFC le fichier du 21 (OK pour le 22)  et mes essais pour le trouver dans les archives web sont vains , 

Par contre  si cela vous intéresse voici le lien pour la publication du site local qui les enregistre systematiquement , https://www.toutmontbeliard.com/  
pour le 21 cela donne :
https://www.toutmontbeliard.com/2020/03/21/coronavirus-covid-19-36-deces-au-total-en-bourgogne-franche-comte/

**Comment by Binnette** [comment]
Voici le bulletin du 21/03. Il ne contient pas beaucoup de données

https://www.bourgogne-franche-comte.ars.sante.fr/system/files/2020-03/2020.03.21_COVID%2019_SITUATION%20BFC.pdf

Si tu as de la dispo, n'hésites pas à faire une pull request :+1:

**Comment by antoan2** [comment]
@Binnette : Je peux faire ca rapidement.

**Comment by melisandeteng** [comment]
Je viens de faire une pull request

**Comment by antoan2** [comment]
Ok, pas de soucis !

**Comment by JiPiBi** [comment]
C'est dommage je voulais me lancer dans la production d'yaml ....

**Comment by Binnette** [comment]
Hello, je viens d'update le CSV et le JSON
