### ISSUE TITLE
Constat sur les données ARS

### ISSUE THREAD

**Issue by JiPiBi** [opencovid19-fr/data#276]
Ce n'est pas une issue , mais un constat que vous avez tous fait et j'arrive avec les carabiniers 

Je trouve incroyable que , outre le faible niveau de diffusion des données numériques , les seules infos disponibles au niveau des ARS ne soient pas standardisées en contenu et format , c'est assez impressionnant que chaque ARS décide de sa communication dans son format ! 

J'espere , mais je n'ai pas de preuves , qu'il y a des données numériques là dessous dans un format commun qui leur permet de travailler , sinon c'est à désespérer. ....

J'avais essayé de communiquer sur le site sante publique pour avoir des détails , ils m'avaient renvoyé dans mes 22 en me disant qu'ils avaient autre chose à faire

**Comment by chamtec** [comment]
> 
> J'avais essayé de communiquer sur le site sante publique pour avoir des détails , ils m'avaient renvoyé dans mes 22 en me disant qu'ils avaient autre chose à faire

Ce n'est pas trop de moment des les agacer avec ça. Mais on pourra en discuter après. Car oui c'est étonnant.

**Comment by Binnette** [comment]
Hello je ferme ce ticket. Je vous invite à continuer cette discussion sur Slack:

https://join.slack.com/t/dataagainstcovid-19/shared_invite/zt-cgsplso2-LIvWeRHlf1ZFIrh~SPj~IA
