### ISSUE TITLE
Projet similaire pour l'ensemble des pays ?

### ISSUE THREAD

**Issue by gredin** [opencovid19-fr/data#283]
Bonjour,

Merci pour ce "méta-projet", où j'ai enfin pu trouver les données compilées sur les hospitalisations et les personnes en réanimation.

Savez-vous s'il existe un "méta-méta-projet" (!) qui propose le même regroupement de données pour chaque pays ?

Voici les sources que j'utilise pour l'instant :
- France : https://github.com/opencovid19-fr/data
- Italie : https://github.com/pcm-dpc/COVID-19/tree/master/dati-andamento-nazionale
- Espagne : https://github.com/datadista/datasets/tree/master/COVID%2019

**Comment by alx** [comment]
Bonjour,

Un projet meta-meta, avec des scraper à écrire s'il en manque:

- https://coronadatascraper.com/
- https://github.com/lazd/coronadatascraper

**Comment by Binnette** [comment]
D'autres ressources ici : opencovid19-fr/dashboard#3
Et plein d'autres ici : https://join.slack.com/t/dataagainstcovid-19/shared_invite/zt-cgsplso2-LIvWeRHlf1ZFIrh~SPj~IA

D'ailleurs, pour continuer cette conversation, merci d'utiliser le Slack
