### ISSUE TITLE
Donnees 22 03 2019 erronées au niveau national

### ISSUE THREAD

**Issue by JiPiBi** [opencovid19-fr/data#285]
De mon coté , j'ai bêtement copié la même erreur que tout le monde avec 16018 alors qu'il suffisait de faire la somme des régions qui elle était correcte, ce qui est génant , car c'était le plus gros delta journalier depuis le début .....

Nouveau test de cohérence à faire à mon avis systématiquement , ce qui ne réglera pas le pb en cas d'anomalie, à part si on pouvait vérifier aussi toutes les données ARS, ce qui n'est pas toujours possible quand les données manquent ....

Un interlocuteur sante publique à alerter en cas de pb  ?

**Comment by Binnette** [comment]
> Un interlocuteur sante publique à alerter en cas de pb ?
Tu as déjà eu ta réponse, ils sont sous l'eau...

> Nouveau test de cohérence à faire à mon avis systématiquement
Non, la majeure partie de nos fichier ont des trous.

Nous avons corrigé toutes les erreurs ce midi.

**Comment by JiPiBi** [comment]
Les données CSSE et Worldometers étaient du coup  elles aussi erronées ..... elles sont maintenant corrigées 

C'est une simple addition ..... Je peux la faire tous les jours  et vous remonter les anomalies au cas où.
Vous m'avez demandé  de vous remonter les problemes de cohérence que je verrais
Mais si  cela ne vous interessait plus, ce n'est pas grave en soi, mais c'est dommage car sur cette erreur les tandances sont sensiblement differentes
