### ISSUE TITLE
Mauvaise localisation des cas

### ISSUE THREAD

**Issue by TristanDewalle** [opencovid19-fr/data#298]
La majorité des cas sont localisés en Polynésie française, au lieu de la France métropolitaine. Cette issue est liée à [Celle ci](https://github.com/CSSEGISandData/COVID-19/issues/1319)

**Comment by Binnette** [comment]
Bonjour merci de préciser précisément ce qui est incorrect dans notre jeux de donnée.
Notre jeux de données est disponible ici : https://github.com/opencovid19-fr/data/blob/master/dist/chiffres-cles.csv

Merci de m'indiquer qu'elles sont les lignes fausses.

**Comment by Binnette** [comment]
D'après le [README](https://github.com/CSSEGISandData/COVID-19/blob/master/README.md) du projet https://github.com/CSSEGISandData/COVID-19, ce dernier ne semble pas utiliser les données de notre projet.

Ce ticket ne concerne donc pas notre projet, je le ferme. Merci de le rouvrir si besoin.
