### ISSUE TITLE
Region Grand Est - chiffres-cles.csv

### ISSUE THREAD

**Issue by pier62350** [opencovid19-fr/data#314]
Il semblerait que la Région Grand Est apparaisse 2 fois dans les données: une fois sous le format "Grand Est" et une fois sous le format "Grand-Est", si j'en crois les autres régions il faut conserver le tout avec un tiret? :)

**Comment by JiPiBi** [comment]
idem avec
 'Auvergne Rhône-Alpes',
 'Auvergne-Rhône-Alpes',

+

'Ile-de-France',
 'Île-de-France'

et plus vicieux entre 

> d et A

"Provence-Alpes-Côte d'Azur",
 'Provence-Alpes-Côte d’Azur',

et pendant qu'on y est , il me semblait qu'ils avaient unifié la Corse ?
 'Corse',
 'Corse-du-Sud',

**Comment by Binnette** [comment]
Salut @pier62350, @JiPiBi, je viens de corriger, merci :+1: 

Les noms corrigés :
- Grand Est
- Auvergne-Rhône-Alpes
- Provence-Alpes-Côte d'Azur
- Île-de-France

Je n'ai pas trouvé de problème sur Corse, Haute-Corse ou Corse-du-Sud.

Si vous voyez d'autre problèmes, n'hésitez pas. :+1:

**Comment by JiPiBi** [comment]
Pour la Corse , je trouvais juste bizarre le niveau Corse à cote de Corse du Sud, il faudra que je regarde à quelle granulaire  vous les associez .

Sinon j'ai un script python qui recherche les valeurs unique utilisées dans les noms donc en parcourant l output je vois à l œil les écarts.  
Je  vais essayer de l ameliorer pour qu il ressorte  les doublons de désignation pour un même code.

Ma remarque sur les bases de données n etait pas complètement gratuite, en utilisant des codes au lieu de nom dans le tableau de saisie. Et ensuite pour le csv vous ajoutez la désignation du code.

**Comment by JiPiBi** [comment]
J'ai fait un bout de code qui ne  me montre pas d'anomalie  sur le champ maille_nom
J'ai aussi jeté un oeil sur le champ source_nom, il  est assez hétéroclite , c'est vous qui voyez :

['ARS Auvergne-Rhône-Alpes',
 'ARS Bourgogne-Franche-Comté',
 'ARS Bretagne',
 'ARS Centre-Val de Loire',
 'ARS Corse',
 'ARS Grand Est',
 'ARS Guadeloupe',
 'ARS Guyane',
 'ARS Hauts-de-France',
 'ARS Hauts-de-France et Préfecture de l’Oise',
 'ARS La Réunion',
 'ARS Martinique',
 'ARS Mayotte',
 'ARS Normandie',
 'ARS Nouvelle-Aquitaine',
 'ARS Occitanie',
 'ARS Pays de la Loire',
 "ARS Provence-Alpes-Côte d'Azur",
 'ARS Île-de-France',
 'Coronavirus-France-Dataset',
 'DSP Polynésie française',
 'Gouvernement Wallis et Futuna',
 'Gouvernement de la Nouvelle-Calédonie',
 'Le Petit Corse',
 'Ministère des Solidarités et de la Santé',
 'OpenCOVID19-fr',
 "Préfecture d'Ille-et-Vilaine",
 'Préfecture de Bretagne',
 "Préfecture de l'Aisne",
 "Préfecture de l'Allier, ARS Auvergne-Rhône-Alpes",
 'Préfecture de la Manche, ARS Normandie',
 'Préfecture de la Somme',
 'Préfecture du Morbihan',
 'Santé publique France',
 'Santé publique France Data']
