### ISSUE TITLE
Informations disponibles dans le dashboard non trouvées dans les data

### ISSUE THREAD

**Issue by JiPiBi** [opencovid19-fr/data#315]
![image](https://user-images.githubusercontent.com/44967630/77441970-5ee40c80-6dea-11ea-831e-ce2d8a53de1c.png)

Essayant de comprendre pourquoi les données disponibles dans le dashboard par exemple pour l'Ile de France sont plus completes que ce que je trouve dans le .csv , j'ai regardé le .json et je ne trouve pas non plus ces données 

SVP est ce que je ne sais pas extraire vos données , ce qui est toujours possible , ou est ce qu'il y a d'autres sources pour le dashboard ?

**Comment by Binnette** [comment]
Le dashboard utilise uniquement le JSON du projet data :wink:

NB : le CSV est souvent moins complet (en terme de colonnes), je viens d'ailleurs de rajouter la colonne 'depistes'.

Peux-tu me dire exactement quelle donnée tu ne retrouves pas ? (jour et granularité)

@+ :wink:

**Comment by JiPiBi** [comment]
Avec l exemple en capture du dessus , j ai tout dit ( sauf si vous avez mis à jour les données depuis).

Par contre je nai pas trouvé ces valeurs dans le json non plus. Mais  je cherche peut-être mal....

**Comment by NicolasGrosjean** [comment]
Sur [la version du fichier d'hier à 22h36](https://raw.githubusercontent.com/opencovid19-fr/data/62f67971270e6bd82c3c1817d90a1f8bb5c5909c/dist/chiffres-cles.json), les données se trouvent à partir de la ligne 38421

![image](https://user-images.githubusercontent.com/13560473/77579411-94682300-6eda-11ea-984f-c44d0029748f.png)

**Comment by JiPiBi** [comment]
Entendu , je n'ai pas retrouvé à quelle date les données ont été mises à jour mais peu importe 

J'avais surtout le probleme de ne pas  savoir que Covid19-fr était devenu une source de données et mon code à tort ne travaillait qu'avec des types de source identifiées 
Il faudrait sans doute que je change mon code pour ne pas tenir compte des sources et qu'il prenne maintenant la moyenne (ou le max ) des valeurs exprimées pour un couple entité+date  , pas si simple pour moi quand on a jusqu'à 3 lignes pour l'information 

Moralité le csv ne m'aide plus beaucoup : ne faudrait il pas que le code qui produit le csv soit fait de telle facon qu'il y ait une seule valeur (le fichier chiffres-clés restant le fichier identifiant les sources

Je vais peut etre en fait surtout ne  plus passer par ce site puisqu'on a un accès direct aux données departementales de data.gouv qui ont l'air très correctes

**Comment by Binnette** [comment]
Je ferme le ticket. Merci de rouvrir si le problème persiste
