### ISSUE TITLE
Info : CSSE ne suit plus les Recovered 

### ISSUE THREAD

**Issue by JiPiBi** [opencovid19-fr/data#317]
Ils ne suivent plus que les confirmed et deaths , c'est un peu moins positif , il ne reste plus pour moi que worldometers mais les données ne sont pas accessibles au delà du lendemain (now+ yesterday)

**Comment by chamtec** [comment]
pourquoi créer une issue ici?

**Comment by JiPiBi** [comment]
J'ai marqué que c'était une info 
On ne sait jamais ca pourrait interesser ceux qui ne s'interessent pas qu'à la France que le site le plus consulté du monde en ce moment a changé le format de ces données accessibles 
Mais comme je n'ai pas le bon motif sur mon autorisation de sortie je rentre à la maison :-)

**Comment by JiPiBi** [comment]
MAJ : le fichier est revenu dans le repo CSSE
