### ISSUE TITLE
Informations Geodes

### ISSUE THREAD

**Issue by JiPiBi** [opencovid19-fr/data#349]
Je viens de découvrir les données disponibles sous GEODES qui sont semble t il exportables et couvrent au niveau departement beaucoup de données : hospitalisation/rea/deces 
Quelque chose m'echappe donc : pourquoi ne pas récupérer ces fichiers  plutot que de faire de la saisie dans des yaml ?

**Comment by Binnette** [comment]
Hello @JiPiBi, ces données sont présentes dans notre fichier depuis le 23/03 :wink:

Si jamais tu vois passer d'autres sources officielles, n'hésites pas :+1: Merci a+

**Comment by JiPiBi** [comment]
Pas de pb , je regarde sur data.gouv en ce moment pour comprendre ce qu ils veulent faire avec ces données 

Pour aller plus loin , est ce que vos yaml sont encore utiles et suivis ?

**Comment by JiPiBi** [comment]
Pour info avec un jeu de données fournies analyse sur le perimetre de AP HP 
depts = ['60','75','78','91','92','93','94','95']

![image](https://user-images.githubusercontent.com/44967630/77547535-9cf63480-6ead-11ea-9c5d-90f5ee344be4.png)

**Comment by JiPiBi** [comment]
Par contre dans vos données ca se complique : on aarive à 3 lignes par region , avec bien sur des chiffres pas toujours cohérents , je commence à douter de la facon de travailler avec la base 

![image](https://user-images.githubusercontent.com/44967630/77555878-1135d580-6eb8-11ea-88b1-1b831eab3021.png)

**Comment by JiPiBi** [comment]
Au fait une info sur une situation que je connais un peu , les données issues des hopitaux faussent les cartes par departement , par exemple les malades du Territoire de Belfort + ceux du Nord du Doubs + ceux de l'Est de la Haute Saone , sont hospitalisés dans le Territoire de Belfort , ce qui fait passer le département au dessus du Bas Rhin et juste en dessous du haut Rhin en ratio hospitalisés/ population (alors qu'il y a moins de 100 hospitalisation d'après les données cartographiées que je vois sur un site vers lequel renvoie data.gouv) 
Donc plus on affine avec des ratio, moins  on est fiable car on parle en terme de population departementale et pas de bassin pour un hopital . Du coup le Doubs s'en sort mieux. Attention à l'utilisation de ces données pour conclure quoi que ce soit sur un departement qui peut etre très hétérogene ....

**Comment by JiPiBi** [comment]
J'ai fait un test sur les données d'hier 24 après avoir mis un peu de code en place pour ma région 
Il y a des écarts minimes par rapport aux données que je suivais sur le site de santé publique 

J'ai un lien direct de chargement des données que j'ai intégré dans mon code 
https://www.data.gouv.fr/en/datasets/r/b94ba7af-c0d6-4055-a883-61160e412115

![image](https://user-images.githubusercontent.com/44967630/77579886-55869d00-6edb-11ea-8809-a939ac6ec13a.png)
