### ISSUE TITLE
Ajout optionnel de l'heure de la source

### ISSUE THREAD

**Issue by EnochMakenp** [opencovid19-fr/data#351]
Bonjour,
certaines sources font les décomptes à 12h, d'autres à 14h, d'autres enfin à minuit :-(

Il faudrait peut-être ajouté une tag time: pour renseigner l'heure en plus de date: quand elle est connue ?

**Comment by Binnette** [comment]
C'est une bonne idée. Je fais passer l'info sur le Slack.
https://join.slack.com/t/dataagainstcovid-19/shared_invite/zt-cgsplso2-LIvWeRHlf1ZFIrh~SPj~IA

Merci :+1:

**Comment by ColinMaudry** [comment]
Bonne idée car ça peut être utile au contributeur, mais pas rendre obligatoire car :

- finalité peu évidente pour la publication des données
- risque d'erreur sur les fuseaux horaires des DROM/COM

Proposition :

ajouter un champ `time` aux objets `source`. L'heure représente idéalement l'heure d'arrêt des stats, mais peut éventuellement être l'heure du communiqué.

**Comment by Binnette** [comment]
C'est fait 6a24469499fc9647f8fb330cccc0247e50fd4611

Et non, l'heure ne concerne pas la source. L'heure concerne la fichier YAML. Exactement comme la date concerne concerne le YAML et pas les sources.
