### ISSUE TITLE
Les données pour la france absente du 18 au 23 mars

### ISSUE THREAD

**Issue by elkolotfi** [opencovid19-fr/data#352]
Bonjour, 

Je remarque que les données du 18 au 23 sont absentes du fichier pour la france. Elles étaient là avant.

**Comment by Binnette** [comment]
Bonjour, pouvez-vous être plus précis ? Vous parlez du fichier CSV ? du JSON ?

**Comment by JiPiBi** [comment]
En tous cas dans le csv , je n'ai pas de trous de données 

![image](https://user-images.githubusercontent.com/44967630/77562152-ee0f2400-6ebf-11ea-8772-436a419783f7.png)

**Comment by Binnette** [comment]
Je viens de vérifier le CSV tout est OK. Les données nationales pour la France sont bien présentes du 18 au 23 mars.

Je ferme le ticket. Merci de le rouvrir si le problème persiste en ajoutant le maximum de détails :+1:
