### ISSUE TITLE
depistes : total cumulé du nombre de personnes dépistées (testées par PCR) missing

### ISSUE THREAD

**Issue by danielw2904** [opencovid19-fr/data#364]
Sorry if I missed it but it seems the number of tests performed is missing from the data. Is it in a different file?

Thanks!

**Comment by Binnette** [comment]
Hi, i guess you are talking about the CSV file ?

**Comment by Binnette** [comment]
I added `depistes` in the CSV through 1eb4c9aefb97e798bd44fa09f62219fe20001b53

Please consider closing this issue if I fixed it :+1:

**Comment by danielw2904** [comment]
Sorry! Yes I was talking about the CSV. Thank you!
