### ISSUE TITLE
ADD * 25/03 (ajout des fichiers manquants)

### ISSUE THREAD

**Issue by Binnette** [opencovid19-fr/data#382]
Hello,

:bulb: pensez à réserver votre fichier en ajoutant un message dans cette issue et à respecter les conventions de nommage des PR (cf [README](https://github.com/opencovid19-fr/data#convention-de-nommage-des-pull-requests))

Des volontaire pour traiter les fichiers suivants SVP :
1. [ ] :hourglass: #388 Ministère des Solidarités et de la Santé : https://www.dailymotion.com/video/x7sxnzg
2. [x] ARS Guyane : https://twitter.com/ars_guyane/status/1242941341786652
3. [x] ARS Bretagne : https://www.bretagne.ars.sante.fr/coronavirus-en-bretagne-point-de-situation-sanitaire-du-mercredi-25-mars-2020-et-mesures-destinees
4. [x] ARS Provence-Alpes-Côte d'Azur https://www.paca.ars.sante.fr/coronavirus-point-de-situation-du-25-mars-2020
5. [x] DSP Polynésie française : https://www.service-public.pf/dsp/2020/03/25/situation-coronavirus-250320/
6. [x] Nouvelle-Calédonie : https://gouv.nc/coronavirus

Pas encore, dispo, mais jetez-y un œil pour voir si les données sont publiées :
1. [x] ARS Auvergne-Rhône-Alpes
    - https://www.auvergne-rhone-alpes.ars.sante.fr/coronavirus-covid-19-0
    - https://twitter.com/search?q=from%3AARS_ARA_SANTE
2. [x] ARS Grand Est
    - https://twitter.com/search?q=from%3Aars_grand_est
    - https://www.grand-est.ars.sante.fr/liste-communiques-presse
3. [x] ARS Hauts-de-France
    - https://www.hauts-de-france.ars.sante.fr/covid-19-actualites
4. Wallis et Futuna : pas de données le 25
    - http://www.wallis-et-futuna.gouv.fr/
    - https://twitter.com/search?q=from%3APrefet986&src=typed_query

Merci d'avance :heart:

**Comment by Eymiks** [comment]
Je m'occupe du MSS.

**Comment by RenaudBCEREMA** [comment]
Fait pour les Hauts de France

**Comment by liszto** [comment]
J'aivas pas vu ton issue mais j'ai fait : 
- PACA
- Guyane 
- Bretagne

**Comment by liszto** [comment]
Je vais faire Grand-Est du coup

**Comment by liszto** [comment]
je fais AURA

**Comment by cofri** [comment]
Je m'occupe de la Polynésie Française.

**Comment by liszto** [comment]
@Binnette il n'est pas fait mention de cas de covid19 dans les communiqué du 25 du tout.
Soit on laisse la journée vide. Soit on peut créer une entrée pour le 25 avec tout à 0 et un lien vers le communiqué du 25 (sachant que celui-ci ne précise rien sur les cas donc potentiellement toujours 0)

**Comment by liszto** [comment]
@Binnette voila ce que ca peut donner en mode très très rapide sans mise en forme. Je bosserai dessus ce soir ou demain. La j'ai juste repris ton post d'hier soir pour l'adapter dans le script.

Pour faire ca plus propre : 
- Avec des checkboxs
- Avec tous les liens au minimum vers les ARS (et si possible vers les communiqués quand les urls sont génériques)
- Avec tous les bons liens pour la SPF
- etc...

![image](https://user-images.githubusercontent.com/408031/77663724-ad75e000-6f7d-11ea-95d9-b5d60d5e6492.png)

**Comment by JLPH987** [comment]
@liszto Je te confirme qu'il n'ai pas fait mention de cas pour Wallis et Futuna car ils ne sont toujours pas touché (l'avantage d'être au milieu de nul part).

**Comment by Binnette** [comment]
@liszto: pas besoin de fichier dans ce cas :)
