### ISSUE TITLE
[QUESTION][IMPROVEMENTS] Création d'un job auto pour les tâches répétitives

### ISSUE THREAD

**Issue by liszto** [opencovid19-fr/data#390]
Hello,
je pourrais plancher sur un job qui se fait chaque jour à un horaire précis pour créer des issues / tâches répétitives.
Exemple d'issue : 
ADD ARS <Region Name> du <Current Day>
et
ADD SPF du <Current Day>
et
ADD Ministère Santé du <Current Day>

Et ajouter dans le corps du message, le lien vers l'ARS ou autre en question pour éviter de perdre du temps en recherche de source. Quand les sources sont connues ou récurrentes.

De cette façon on pourrait avoir une trace plus précise de ce qui est fait ou pas en terme de jour / région. Car il m'arrive personnellement souvent de me balader dans la hiérarchie pour voir ce qui est fait ou pas.

Et quand on fait une issue on la prend et on la cite dans sa PR (et inversement) de cette façon on garde une traçabilité propre de chaque tache quotidienne à faire.

Qu'est-ce que vous en pensez ?

Edit : @Binnette ca t'éviterai de devoir créer ce genre de ticket #382

**Comment by Binnette** [comment]
Hello, si on veut aller au bout du truc, il faudrait que les tâches soient créées au moment de la publication des communiqués de presse.

Et c'est possible, car les ARS proposent des flux RSS de leur page "actualité". 
https://www.hauts-de-france.ars.sante.fr/liste-rss

Idem pour les vidéos DailyMotion, il doit bien avoir un flux RSS ou un truc semblable.

Petite blague du Professeur, nous avons déjà son discours de ce soir dispo ici :
https://solidarites-sante.gouv.fr/soins-et-maladies/maladies/maladies-infectieuses/coronavirus/article/points-de-situation-coronavirus-covid-19

Le PDF du professeur est nommé 25 mars, mais dans l'entête est marqué 26 mars 😄  
https://solidarites-sante.gouv.fr/IMG/pdf/point_de_situation_mercredi_25_mars_.pdf

**Comment by JiPiBi** [comment]
J'ai essayé de faire de la recup des pdf en automatiques , j'y arrive à peu près sur 2 ARS que je suis  , mais en utilisant des variantes de noms de fichier car il n'y a pas de standards de noms de pdf et en plus ils varient . Mais ma méthode n'est peut etre pas la bonne (j'ai essayé de lire le dossier complet mais j'ai été rejeté , je n'ai pas insisté)

**Comment by liszto** [comment]
@Binnette j'avais pas pensé à ça (je n'utilise que rarement les flux RSS) et surtout certains ne publient pas toujours voire rarement. Comme l'ARS Guyane qui met les communiqués sur son Twitter directement.

Je ne pensais pas qu'il y avait besoin d'aller aussi loin mais c'est pas bête :D 

Moi c'était plus déclenché une création déjà basique des tâches à 18h. Heure où les communiqués commencent souvent à tomber les uns après les autres. (ou plus tôt). Ca permettait déjà de faire une v1 du truc pour créer une organisation dans la répartition des fichiers à créer et surtout un suivi plus simple.

Après pourquoi pas rajouter une v2 avec le déclenchement induit par les flux RSS ?

**Comment by JiPiBi** [comment]
@liszto 
Svp avez vous un exemple de lien sur un communiqué concernant  IDF recemment ?

**Comment by Binnette** [comment]
@liszto : pour info, on peut aussi faire des TODO list directement dans les issues. Comme ça pas la peine de créer 20 issues par jour, une seule issue est nécessaire :wink:

**Comment by liszto** [comment]
@Binnette c'est pas faux !
Je trouve juste ça moins clair. Mais tout n'est que question de point de vue sur ce genre de question ;)

**Comment by Binnette** [comment]
@liszto, ben justement je lui indique les communiqués les "plus récents" comme demandé :sweat_smile: :wink:

**Comment by liszto** [comment]
😅

**Comment by liszto** [comment]
@Binnette voila ce que ca peut donner en mode très très rapide sans mise en forme. Je bosserai dessus ce soir ou demain. La j'ai juste repris ton post d'hier soir pour l'adapter dans le script.

Pour faire ca plus propre :

Avec des checkboxs
Avec tous les liens au minimum vers les ARS (et si possible vers les communiqués quand les urls sont génériques)
Avec tous les bons liens pour la SPF
etc...

![image](https://user-images.githubusercontent.com/408031/77663956-ef068b00-6f7d-11ea-8687-ae971405a12c.png)

**Comment by Binnette** [comment]
C'est pas mal :+1: Pense aux checkbox `- [ ]` =>
- [ ] test

Et effectivement pas la peine de mettre les url en entier [Site web](), [Twitter]() suffisent :wink:

Ou alors pour les checkbox :

Bulletin réservé :
- [ ] AURA
- [ ] PACA 

PR faites (need review) :
- [ ] AURA
- [ ] PACA

PR relue :
- [ ] AURA
- [ ] PACA

**Comment by liszto** [comment]
Le "bulletin réservé" risque de vous imposer un gros travail je ne le mettrais peut-être pas :D

**Comment by Binnette** [comment]
Vu, ensemble... je pensais que tout le monde pouvait cliquer sur l'une de mes checkbox...
Donc on va rester sur un mode, celui qui veut réserver, il ajoute un message du style "Je prends le bulletin AURA"

**Comment by ColinMaudry** [comment]
Je suis d'accord que des issues individuels ça fait beaucoup d'issues mais :

- voir 22 issues non fermés, ça montre qu'il y a du taf, et qu'il faut se magner :)
- dans /issues on peut voir d'un coup d'oeil quels issues sont pas pris, car ils n'ont pas de photo de profil "assigned"
- on peut cross référencer l'issue et la PR, et peut-être même fermer automatiquement l'issue quand la PR est mergée avec un comment "closed #[numéro d'issue]" dans le dernier commit.

**Comment by liszto** [comment]
Faut juste se mettre tous d'accord sur ce que l'ont veut.
Dans mes tests avec des samples de mon côté.
En ce moment j'arrive à : 
Envoyer un message à une issue
Créer une issue
Créer de multiple issue en une fois.

En gros tout ce qu'on veut faire dans un cas ou dans l'autre.
Reste à se mettre d'accord sur ce qu'on veut :D 

Dès que j'ai le temps de me poser il faut que j'écrive un json pour chaque issue potentielle. Et faire un fichier ou je les regroupe toutes comme ça on peut faire la solution 1 ou la 2. Ca ne me coutera pas spécialement plus de temps ou de code normalement :D 

Dès que je peux me dégager du temps je peux faire ça sur une demie journée à peine je pense.
