### ISSUE TITLE
ARS Provence-Alpes-Côte d'Azur : perte des données deces

### ISSUE THREAD

**Issue by gbrault** [opencovid19-fr/data#395]
Bonjour,

aujourd'hui, la colonne deces a toutes ses valeurs à 0. (source_nom='ARS Provence-Alpes-Côte d'Azur')

Est-ce que la définition des données a changée?

Merci.

**Comment by liszto** [comment]
@gbrault je pense que c'est parce que la PR #387 n'est pas encore mergé dans le master du projet.

**Comment by Binnette** [comment]
La PR est mergée et je viens de régénérer le CSV et le JSON.

@gbrault : je ferme l'issue. Merci de la rouvrir si le problème persiste. Si c'est le cas, nous donner un exemple de donnée qui n'est pas bonne (date, département et source). Merci d'avance. :+1:
