### ISSUE TITLE
Polynesie Francaise et Nouvelle Caledonie

### ISSUE THREAD

**Issue by JiPiBi** [opencovid19-fr/data#403]
Les valeurs sont bien dans le CSV , mais ils ne semblent pas remonter dans les données affichées sur le site SPF , et visiblement le total déclaré tous les jours pour la France n'en tient pas compte 

Qu'en pensez vous ?

**Comment by Binnette** [comment]
Je n'en penses pas grand chose à part que Santé Publique France ne fait pas partie de notre projet.

Donc tu peux éventuellement les contacter pour leur signaler le problème, mais je doute qu'ils prennent en compte ta remarque rapidement.

**Comment by JiPiBi** [comment]
Votre réponse me surprend un peu , je croyais qu'on pouvait parler ici des données que vous collectez sur la France.

Du coup quand je prends des données dans le fichier chiffres-cles avec pays = France , elles représentent quoi ?

**Comment by Binnette** [comment]
Même réponse que dans l'autre ticket. Le Slack est la bonne place pour les discussions. Dans le projet data, nous nous contentons de récupérer les données. 

> Du coup quand je prends des données dans le fichier chiffres-cles avec pays = France , elles représentent quoi ?

Le fichier CSV (ou JSON) se contente de regrouper toutes les données disponibles dans les différentes sources. J'espère que ça réponds à la question. Sinon, il reste le Slack.
