### ISSUE TITLE
Question sur les guéris 

### ISSUE THREAD

**Issue by JiPiBi** [opencovid19-fr/data#404]
Bonjour
Quand j'additionne les valeurs hosp + gueris +deces (source opencovid-fr)  pour differentes régions , je ne retrouve pas le total confirmés 
Explique t on la difference par des personnes confirmées ,  qui sont confinés ou qui sont guéries, sans etre passés par l'hopital ?

**Comment by Binnette** [comment]
Hello @JiPiBi, pour te faire une meilleure idée je t'encourage à regarder différents bulletins (France, région, etc). Tu veras à chaque fois qu'il sont bourrés d'imprécisions et d'erreurs. Des fois, le bulletin donne le nombre de cas... et des fois non. Pareil pour toutes les autres données. :sweat_smile: 

Les trous que tu constates viennent des données manquantes ou erronées des bulletins.

**Comment by JiPiBi** [comment]
La je suis sur les dernieres donnees opencovid , donc je suis perplexe car les écarts sont vraiments importants avec les confirmés 25 à 30% sur ce que je vois

**Comment by Binnette** [comment]
Question à poser sur le Slack. Les vrais data analyst seront certainement content d'en discuter.
