### ISSUE TITLE
Lien vers source invalide

### ISSUE THREAD

**Issue by quarantin** [opencovid19-fr/data#423]
Le fichier suivant contient des liens hypertext vers les différentes sources d'information: https://raw.githubusercontent.com/opencovid19-fr/data/master/dist/chiffres-cles.csv

Cependant, ce lien est cité à plusieurs reprise mais renvoi une erreur HTTP 404 indiquant que la page n'existe pas:
https://www.santepubliquefrance.fr/maladies-et-traumatismes/maladies-et-infections-respiratoires/infection-a-coronavirus/articles/cas-de-pneumonies-associees-a-un-nouveau-coronavirus-2019-ncov-a-wuhan-en-chine

Par exemple:
```
2020-01-24,departement,DEP-33,Gironde,1,,,1,,,Santé publique France,https://www.santepubliquefrance.fr/maladies-et-traumatismes/maladies-et-infections-respiratoires/infection-a-coronavirus/articles/cas-de-pneumonies-associees-a-un-nouveau-coronavirus-2019-ncov-a-wuhan-en-chine,sante-publique-france
```

**Comment by Binnette** [comment]
Bonjour @quarantin, je viens de modifier le CSV pour ajouter la colonne `source_archive`.

En fait, le problème vient du fait que les différents site web suppriment leurs pages ou les écrasent. Du coup, nous avons pris le pas d'archiver ces pages web sur archive.org. Donc dans la nouvelle colonne `source_archive` vous trouverez un lien vers les pages archivées.

Merci d'avoir rapporté ce problème :+1: Je l'ai corrigé :wink: 
Bonne journée.
