### ISSUE TITLE
Nombre de cas confirmés manquant pour le 03/26 et 03/27

### ISSUE THREAD

**Issue by qgolsteyn** [opencovid19-fr/data#435]
Je suis bénévole pour le [Covid Atlas Project](https://github.com/lazd/coronadatascraper) et nous avons remarqué qu'il n'y a plus de nombres de cas confirmé au niveau régional à partir du 03/26. Est ce que ces données ne sont plus reportées par le gouvernement ou seront-elles disponibles plus tard?

**Comment by dataProjectVS** [comment]
Bonjour,

Effectivement depuis le 26/03 plus de données régionales pour les cas confirmés. Si on peut aider à les récupérer n'hésitez pas.

Merci !

**Comment by Binnette** [comment]
Oui c'est normal que ces données soient absentes. Les ARS ne les donnent plus.
Je vous invite à regarder les PDF et les pages pointées par les attributs (ou colonnes) sources et archive_source.

Si vous trouvez des bulletins mentionnant ces données, je vous invite à créer des issues en postant les liens vers ces bulletins (ou à nous faire directement un pull request cf README)

Bonne journée.
