### ISSUE TITLE
Discussion en cours : arrêter la colecte des données à la main ?

### ISSUE THREAD

**Issue by Binnette** [opencovid19-fr/data#436]
Bonjour,

Une discussion est en cours sur Slack sur **l'utilité de continuer la collecte à la main des données**.

Merci de vous exprimer sur slack (**et sur Slack uniquement**) à ce sujet.

Lien vers la discussion : https://dataagainstcovid-19.slack.com/archives/CV3M7RE8Y/p1585342152122100

Lien pour rejoindre Slack : https://join.slack.com/t/dataagainstcovid-19/shared_invite/zt-cgsplso2-LIvWeRHlf1ZFIrh~SPj~IA

:warning: Merci de ne poster aucun message dans cette issue. Merci d'utiliser Slack. Je supprimerai les message de cette issue, car votre message sera beaucoup plus lu et commenté sur Slack. Merci de votre compréhension.

**Comment by jessylenne** [comment]
Bonjour, l'issue étant toujours ouverte j'imagine que le sujet n'est pas clos.

Le lien d'invitation slack est h.s. pourriez vous le renouveler svp ? 

Merci d'avance !

**Comment by jdesboeufs** [comment]
La collecte s'est stoppée d'elle-même, rendue obsolète par la publication des mêmes données par les autorités.
Encore merci à tous pour ce formidable effort collectif !!
