### ISSUE TITLE
ARS Bretagne 2020-03-16

### ISSUE THREAD

**Issue by marion-paclot** [opencovid19-fr/data#44]
Indiquez que vous gérez cette date x ARS avant de vous lancer. Evite les multiples pull requests sur le même sujet. Merci

**Comment by Eymiks** [comment]
Bonsoir, je m'en occupe pour ce soir.

**Comment by Binnette** [comment]
@marion-paclot, @jdesboeufs, @Eymiks : j'ai mis en place un "projet" pour gérer les tâches quotidiennes. Je vous laisse jeter un œil. C'est un Kanban tout simple. A voir si on peux l'utiliser :+1:

Cliquez sur "Projects" en haut de page ou sur le lien: https://github.com/opencovid19-fr/data/projects/1

**Comment by marion-paclot** [comment]
J'en pense du bien. Je ne suis pas du tout au point sur Github, aussi la seule question que je me pose est : une fois que la carte du jour est traitée, est-ce qu'on peut la remettre en to-do avec date suivante facilement ?
