### ISSUE TITLE
ARS Grand-Est 2020-03-16

### ISSUE THREAD

**Issue by marion-paclot** [opencovid19-fr/data#47]
Indiquez que vous gérez cette date x ARS avant de vous lancer. Evite les multiples pull requests sur le même sujet. Merci

**Comment by AntoineAugusti** [comment]
Je prends 👍

**Comment by AntoineAugusti** [comment]
@Binnette Ça n'a pas été fait encore

**Comment by Binnette** [comment]
J'ai confondu avec une autre tâche. Merci :+1:
