### ISSUE TITLE
ASR Occitanie - 31/03/2020

### ISSUE THREAD

**Issue by mqu** [opencovid19-fr/data#473]
je prends. Je vous fais un PR dans qq minutes, cordialement, Marc.

**Comment by mqu** [comment]
désolé, j'ai fait une mauvaise manip pour le PR ; le fichier est là : https://github.com/mqu/data/blob/master/agences-regionales-sante/occitanie/2020-03-31.yaml

**Comment by mqu** [comment]
fait ; je pense que c'est OK. Merci.

**Comment by mqu** [comment]
petite erreur sur la date : time: 19:00 conviendrait mieux.

**Comment by abdoulsn** [comment]
Merci, @mqu
