### ISSUE TITLE
Rafraîchissement des données?

### ISSUE THREAD

**Issue by gbrault** [opencovid19-fr/data#475]
Avec le code suivant
```
import pandas as pd
covid19=pd.read_csv('https://raw.githubusercontent.com/opencovid19-fr/data/master/dist/chiffres-cles.csv')
```
la selection
```
covid19[(covid19['date']=='2020-03-28')]['granularite'].unique()
```
donne
```
array(['collectivite-outremer', 'departement', 'pays', 'region', 'monde'],
      dtype=object)
```
et à partir de là
```
covid19[(covid19['date']=='2020-03-30')]['granularite'].unique()
```
donne
```
array(['departement', 'pays', 'region'], dtype=object)
```
(ça s'arrête au 30).
Est-ce normal?

**Comment by JiPiBi** [comment]
Normal je ne sais pas , mais regardez la date de mise à jour du fichier dans le répertoire , elle date effectivement de 2 jours 

Vous pouvez aussi obtenir des données qui sont très semblables car c'est la source commune(avec moins d'ancienneté ) sur data.gouv.fr

**Comment by dataProjectVS** [comment]
Bonjour,

Merci à ceux qui ont bossé sur ce projet. Plus de MAJ globale depuis le 31/03 et plus de data par région depuis le 26/03. Je pense que les gens ont arrêté de mettre à jour, je comprends ça doit être très chronophage.

Auriez-vous une source directe pour l'évolution des cas confirmés, décès et réa par région FR ? J'ai les infos globales par pays mais c'est moins granulaire : 

https://data.humdata.org/dataset/novel-coronavirus-2019-ncov-cases 
(données J-1, j'utilise la version "narrow")

Merci d'avance !

**Comment by JiPiBi** [comment]
Le lien permanent que j utilise qui donne un détail départemental sauf sur les confirmés.  

https://www.data.gouv.fr/fr/datasets/r/63352e38-d353-4b54-bfd1-f1b3ee1cabd7

**Comment by gbrault** [comment]
Merci @JiPiBi: est-ce que vous avez la définition des colonnes svp?

dep | sexe | jour | hosp | rea | rad | dc

et pour le sexe 0,1,2 correspond à quoi?
Merci

**Comment by JiPiBi** [comment]
Normalement les métadonnées sont accessibles sur le site data.gouv
Dep departement
0 est la somme de 1 et 2

hosp = présents en hosp à la date
rea= en réanimation,  inclus dans hosp
rad = retour à  domicile = guéris même si restent très fatigués 
dc = décédés

**Comment by dataProjectVS** [comment]
Oui j'avais vu ce flux aussi mais effectivement il manque les cas confirmés, même si on devra s'en contenter en attendant.

Je ne sais pas si vous avez remarqué mais ce dash qui se connecte sur les données (a priori) opencovid19-fr est bien à jour : https://dashboard.covid19.data.gouv.fr/

Pour les cas confirmés on a la source US John Hopkins pour compléter en attendant (cf. mon précédent post).

**Comment by JiPiBi** [comment]
@dataProjectVS 

Ce dashboard est issu du meme github que celui-ci en mettant dashboard à la place de data. Donc même equipe.

Pour JHU  , qualité instable. Voir le nombre de issues. Ils travaillent aussi en reprenant maintenant les données worldometers.

**Comment by dataProjectVS** [comment]
Oui pas 100% nickel non plus côté JHU mais je n'ai pas eu de souci de MAJ depuis que je l'utilise (une semaine environ).

Est-ce que Worldometers est plus stable ? Je n'ai pas encore testé. Pour le dashboard oui j'ai vu que c'était la même équipe mais je me demandais quelle(s) source(s) ils utilisaient car quand ce n'était pas à jour côté data. ça l'était côté dashboard.

**Comment by gbrault** [comment]
Les valeurs par départements sont actualisées effectivement.

**Comment by JiPiBi** [comment]
la copie du fichier qu'on trouve sur data.gouv qui sert à alimenter chiffres-cles.csv est dans le dossier sante-publique-fr

**Comment by JiPiBi** [comment]
Remarque : si vous regardez de près le fichier , vous verrez qu'il y a pour le 1/4 deux lignes avec des chiffres differents pour la France au 1/04
2020-04-01,pays,FRA,France,56989,4032,6017,24639,10935,,Ministère des Solidarités et de la Santé,,,ministere-sante
2020-04-01,pays,FRA,France,,4032,5940,24543,10934,,OpenCOVID19-fr,,,opencovid19-fr

si on fait les cumuls par jour du fichier par departement , au 1/4  on retrouve les chiffres de la 2eme ligne  
mais la ligne Mayotte au 1/4 de ce fichier donne 
2020-04-01,departement,DEP-976,Mayotte,,0,0,0,1,,Santé publique France Data,,,sante-publique-france-data

alors qu'au 1/4 Mayotte a 101 cas , 1 deces et 10 gueris et 3 personnes en rea (worldometers)

Pour info Polynesie et Nouvelle Caledonie ne sont pas pris en compte , JHU annonce 53 cas pour les 2 territoires 
worldometers annonce 53 cas 1 gueris , 1 en rea 

Voilà , voilà .....

**Comment by gbrault** [comment]
Du coup, je doit prendre covid19[(covid19['maille_nom']=='France') & (covid19['source_type']=='ministere-sante')]!
Merci @JiPiBi 
![image](https://user-images.githubusercontent.com/7886676/78262476-ea535100-7500-11ea-8e0f-20a7e9fd6524.png)

**Comment by gbrault** [comment]
Ou avec le hospitalisation, ce qui a mon sens est plus significatif
![image](https://user-images.githubusercontent.com/7886676/78263209-f390ed80-7501-11ea-8a41-aa5d662d7ee6.png)

**Comment by gbrault** [comment]
![image](https://user-images.githubusercontent.com/7886676/78264788-e7a62b00-7503-11ea-995e-6ed207bbddff.png)

**Comment by gbrault** [comment]
![image](https://user-images.githubusercontent.com/7886676/78264905-0b697100-7504-11ea-9a2f-a87e6eee9f9f.png)

**Comment by gbrault** [comment]
Mais il faut faire attention aux modèles mathématiques: [selon ](https://fr.wikipedia.org/wiki/Mod%C3%A8les_compartimentaux_en_%C3%A9pid%C3%A9miologie#Repr%C3%A9sentation_math%C3%A9matique_%C3%A0_l'aide_d'%C3%A9quations_diff%C3%A9rentielles) 

> 

>

**Comment by JiPiBi** [comment]
Ca marche pourtant bien en Italie en echelle log , peut etre qu'il y a moins de puces et de rats de nos jours 

![image](https://user-images.githubusercontent.com/44967630/78277554-05c85700-7515-11ea-8f05-66178f5f2a4d.png)

**Comment by gbrault** [comment]
Je vous engage à regarder https://github.com/TomNicholas/coronavirus

**Comment by JiPiBi** [comment]
@gbrault 
Merci pour le lien 
Merite d'y passer quelques heures pour en comprendre toute la substantifique moelle .....
L'interet est que tout ce que le notebook permet de jouer avec les valeurs 

Globalement vu d'avion conforme à ce qu'on entend déjà y compris le profil en tole ondulée qd on relache la pression de la distanciation.

Ce qui pose d'ailleurs la question de la suite , comment déconfiner sans faire des tests massifs sur 60 000  000 de personnes , ce qui prendra un certain temps comme le fut du canon pour refroidir,   et d'ici là le corona peut revenir sous la meme forme ou une autre ( le modèle peut peut etre évoluer pour tenir compte du risque de perte d'immunité progressif , sans vaccination qui elle meme doit s'adapter à l'évolution du corono , idem grippe )
Bref nous n'en sommes qu'au début

**Comment by gbrault** [comment]
@JiPiBi : votre conclusion était l'objet de mes recherches... Et pour essayer de mesurer ce que début veut dire!

**Comment by JiPiBi** [comment]
Pour info, je suis en cours de suivi d un MOOC  sur Coursera portant sur la compréhension de ce qu'est une épidémie et les éléments de suivi , c est fait par JHU  donc assez sérieux.

**Comment by Binnette** [comment]
Bonjour, on dirait qu'il n'y a plus d'issue à proprement parler dans ce ticket, donc je le ferme.

Je vous invite à continuer votre discussion sur Slack. Je suis persuadé que la communauté serait intéressée par vos discussions, diagrammes, calculs, etc.

Lien vers notre Slack : https://join.slack.com/t/dataagainstcovid-19/shared_invite/zt-cgsplso2-LIvWeRHlf1ZFIrh~SPj~IA
