### ISSUE TITLE
Données Manquantes ?

### ISSUE THREAD

**Issue by PaulMuadDib** [opencovid19-fr/data#488]
Bonjour,
Je tente de modéliser la trajectoire épidémique du covid-19 en France.
Je l'ai pour l'instant fait au niveau national avec un modèle SIR augmenté de 2 sous populations.

![DailyFrance02042020](https://user-images.githubusercontent.com/4218461/78452308-e6533a80-768a-11ea-8796-5bbfaeedb06c.jpg)

![CumulatedFrance02042020](https://user-images.githubusercontent.com/4218461/78452411-6da0ae00-768b-11ea-805a-0d9a2095b135.jpg)

Je souhaitais poursuivre en estimant un modèle par région ou par département ainsi que les flux entre ces modèles régionaux / départementaux, mais lorsque je regarde mon département (le 06), je constate qu'il manque pas mal de données sur les nombres d'infections confirmées (rien à partir du 22/03, parcellaire avant): est-ce du à l'agrégation des données ? (l'ARS PACA a pourtant communiqué ces données). 

Bien cordialement,
JFB

**Comment by abdoulsn** [comment]
Bonjour, en un moments données les sources ne communiquait pas de casConfirmes dans les ARS a moins que ça soit par un autre canal.

**Comment by Binnette** [comment]
Bonjour Paul Atréides,

Oui c'est normal qu'il y ai des "trous". La plupart des ARS ont arrêté de donner le nombre de cas confirmés. Donc malheureusement, il n'y a rien que l'on puisse faire. Si toutefois, tu trouves un bulletin d'ARS qui donne bien ces cas, merci de nous donner le lien vers ce bulletin. (Voir même, nous faire une 'pull request' directement avec les données, cf le README).

> Le décompte quotidien des nouveaux cas est désormais réalisé par l’agence nationale Santé publique France. 

Extrait de : https://web.archive.org/web/20200326204057/https://www.paca.ars.sante.fr/coronavirus-en-provence-alpes-cote-dazur-point-de-situation-au-26-mars

Je ferme ce ticket, merci de le rouvrir si tu trouves un bulletin ARS "complet" 😉 

Bonne journée, "que puisse ton eau, se mêler à la notre". --Stilgard
