### ISSUE TITLE
ARS Ile-de-France 2020-03-16

### ISSUE THREAD

**Issue by marion-paclot** [opencovid19-fr/data#49]
Indiquez que vous gérez cette date x ARS avant de vous lancer. Evite les multiples pull requests sur le même sujet. Merci

**Comment by AntoineAugusti** [comment]
Je prends 👍

**Comment by Eymiks** [comment]
Je viens de trouver ce tweet : https://twitter.com/ARS_IDF/status/1239285741693227009
A priori L'ARS IDF ne communiquera plus de chiffres

**Comment by AntoineAugusti** [comment]
[Le dernier communiqué] publié semble aller dans le même sens 😢 https://www.iledefrance.ars.sante.fr/coronavirus-covid-19-points-de-situation

**Comment by AntoineAugusti** [comment]
Je ferme, pas de nouveaux communiqués depuis.
