### ISSUE TITLE
Prise en compte des Confirmés hors Hopital

### ISSUE THREAD

**Issue by JiPiBi** [opencovid19-fr/data#491]
Je viens de voir sur le site de SPF une valeur de 22361 pour les cas en ESMS, comptez vous le prendre en compte  ? il semblerait  que ce soit une autre appellation des EPHAD, puisque dans la case des décès le même terme de ESMS est utilisé et pas celui d'EPHAD pour les sources d'infos

**Comment by Binnette** [comment]
Salut @JiPiBi, c'est une bonne idée, merci :+1: 

Tu te sens de nous faire une pull request pour ajouter cet attribut dans les fichiers SPF ?
`casEsms: xxxx`

**Comment by JiPiBi** [comment]
je ne suis pas sur d'avoir compris comment votre site fonctionne pour les mises à jour du fichier chiffres clés.csv  , c'est le fichier build.js qui semble faire les mises à jour de chiffres clés. csv , donc il faudrait modifier  ce fichier ?
c'est du javascript, et moi  je suis plus à l'aise en python :-(
Je ne connais donc pas assez pour prendre en compte sans qu'on me tienne  la main ....

**Comment by JiPiBi** [comment]
Par rapport à ce que j'avais écrit, EPHAD est inclus dans ESMS . A coté des personnes agées , il y a les établissements pour les plus jeunes EMS  (exemple des ADAPEI je pense)

**Comment by Binnette** [comment]
Pour contribuer tout est indiqué dans le README :wink: 
Tu auras zéro ligne de code à faire. je me chargerait du build.js par contre je veux bien que tu modifies les yaml pour ajouter `casEsms` sur les différents fichiers :+1:

**Comment by JiPiBi** [comment]
Derniere  remarque @jdesboeufs sur Slack disait que les cas ESMS n'étaient pas de même nature que les cas en Hopital car non tous confirmés et donc sont un mélange de cas confirmés et de cas suspectés .
Si vous etes d'accord pour continuer , il faudrait aussi l'écrire quelque part (READ.ME ?)
Ajouter le casEsms dans les différents fichiers veut dire l'ajouter dans les fichiers ministere sante uniquement  ?  
j'ai noté les chiffres du 5/4 22361 -  6/4 23620  7/4 30902 8/4 30902 # inchangé. Faut il modifier ces 4 fichiers ?

**Comment by Binnette** [comment]
Le champ Décès EHPAD est présent dans le README **global** donc pas nécessaire de modifier les autres README. Le nouveau champ doit également être ajouté dans le README global.

Attention, je crois que tu confond Ministère de la santé (qui fait des bulletins vidéos) et Santé publique France qui fait des bulletins sous forme de page web sur son site.

**Comment by JiPiBi** [comment]
Pour etre d'accord sur ce qui est à faire  : est ce que c'est bien ce repertoire 
![image](https://user-images.githubusercontent.com/44967630/78906983-5a715200-7a80-11ea-9d8f-f661c2c22a46.png)
 et ces fichiers 

![image](https://user-images.githubusercontent.com/44967630/78907040-6e1cb880-7a80-11ea-8f02-39c922d915f0.png)

**Comment by JiPiBi** [comment]
Avec la distinction des categories confirmes et suspectés en ESMS : faut il créer 1ou  2 champs
![image](https://user-images.githubusercontent.com/44967630/78937879-835e0b00-7ab1-11ea-8ae8-13a4b32d61a8.png)

**Comment by Binnette** [comment]
Salut @JiPiBi, peux tu coller un lien veres le bulletin que contient ces données. Je n'ai pas compris, si c'était des données du ministère ou de Santé publique France ?

**Comment by JiPiBi** [comment]
https://www.santepubliquefrance.fr/content/download/243797/2565951

**Comment by JiPiBi** [comment]
Pour ce qui est des yaml à modifier et à soumettre , SVP me donner leur liste explicite et exhaustive

**Comment by JiPiBi** [comment]
Pour etre plus complet il y a en fait 2 tableaux 

![image](https://user-images.githubusercontent.com/44967630/78995176-10e93b80-7b42-11ea-8352-ef736665fc07.png)
