### ISSUE TITLE
ARS Normandie 2020-03-16

### ISSUE THREAD

**Issue by marion-paclot** [opencovid19-fr/data#50]
Indiquez que vous gérez cette date x ARS avant de vous lancer. Evite les multiples pull requests sur le même sujet. Merci

**Comment by AntoineAugusti** [comment]
Je prends 👍

**Comment by AntoineAugusti** [comment]
L'ARS Normandie n'a rien publié pour le 16 et le 17 et a sauté directement au 18 mars https://www.normandie.ars.sante.fr/liste-communiques-presse
