### ISSUE TITLE
Changement de format à éviter

### ISSUE THREAD

**Issue by Christian-G-UT** [opencovid19-fr/data#526]
Au fur et à mesure que de nouvelles données sont disponibles le format de la base de données est changé. Cela est problématique car cette base de données est souvent reutilisée par d'autres projet, sur Github ou ailleurs ce qui requiert de s'adapter au nouveau format. Il serait peut être souhaitable à partir de maintenant de rajouter les nouvelles données à la fin plutôt que de changer l'ordre des entrées dans la base de données.

**Comment by jdesboeufs** [comment]
Je réponds tardivement à cette question mais l'ordre des champs n'est pas prescriptif, c'est à votre schéma de gérer ça.
