### ISSUE TITLE
ARS Pays-de-Loire 2020-03-16

### ISSUE THREAD

**Issue by marion-paclot** [opencovid19-fr/data#53]
Indiquez que vous gérez cette date x ARS avant de vous lancer. Evite les multiples pull requests sur le même sujet. Merci

**Comment by racilk** [comment]
Sur ce bulletin d'information, il y a toujours le nombre de cas confirmés (109) mais les données départementales ne sont plus disponibles.

https://www.pays-de-la-loire.ars.sante.fr/system/files/2020-03/2020-03-16-bulletin%20information%20COVID-19_0.pdf
