### ISSUE TITLE
Données opencovid19-fr en RDF requêtables en SPARQL

### ISSUE THREAD

**Issue by frmichel** [opencovid19-fr/data#533]
Bonjour à toutes et tous, 

Bravo pour ce travail de consolidation. 

Une information pour ceux que cela intéresse. J'ai produit un mapping des données consolidées vers une représentation RDF utilisant le vocabulaire [défini par Schema.org](http://blog.schema.org/2020/03/schema-for-coronavirus-special.html) spécifiquement pour le cas de la pandémie de Covid19.

Chaque rapport est représenté comme un [SpecialAnnouncement](https://schema.org/SpecialAnnouncement) et les nombres de cas (hospitalisés, en réa, décédés etc.) sont des [Observation](https://schema.org/Observation) donnés par la propriété [diseaseSpreadStatistics](https://schema.org/diseaseSpreadStatistics).
Sont aussi associées à l'announcement la date et la zone géographique.

Ces données sont requêtables via notre [endpoint SPARQL](https://covid19.i3s.unice.fr/sparql), elles sont dans un named graph `http://ns.inria.fr/covid19/graph/opencovid19-fr`. Voici un exemple hébergé sur un serveur Virtuoso : http://covid19.i3s.unice.fr:8890/describe/?url=nodeID%3A%2F%2Fb45777759&sid=182

La transformation elle-même est faite par un [SPARQL micro-service](https://github.com/frmichel/sparql-micro-service) accessible ici:
https://sparql-micro-services.org/service/covid19/casesFrance
Exemple pour l'invoquer :
```
Q=construct%20where%20%7B%20%3Fs%20%3Fp%20%3Fo%20%7D
curl -H "accept: text/turtle" "https://sparql-micro-services.org/service/covid19/casesFrance?query=${Q}"
```
**Attention** toutefois, chaque requête SPARQL soumise au micro-service entraine la transformation de toutes les données en RDF donc ça prend du temps.

Si cela vous intéresse et vous pose des questions n'hésitez pas à me contacter.

**Comment by frmichel** [comment]
Une mise à jour du graphe http://ns.inria.fr/covid19/graph/opencovid19-fr est disponible sur un nouveau SPARQL endpoint : http://covidontheweb.inria.fr/sparql
A noter que les URIs sont toujours déréfencées vers l'ancien SPARQL endpoint (covid19.i3s.unice.fr).

**Comment by frmichel** [comment]
Bonjour, tous les rapports journaliers ont maintenant des URI uniques. Exemple: http://ns.inria.fr/covid19/opencovid19fr/announcement/DEP-75/2020-08-19

J'ai aussi mise en place un système pour automatiser la mise à jour du graph tous les jours. 

Tout est là : https://github.com/frmichel/sparql-micro-service/tree/master/services/opencovid19fr/dailyCases_sd et annoncé là : https://twitter.com/franck_michel2/status/1296478689266475011

**Comment by jdesboeufs** [comment]
J'archive mais n'hésitez pas à publier des MAJ.
