### ISSUE TITLE
Données résultantes : cas confirmés ?

### ISSUE THREAD

**Issue by j-bacal** [opencovid19-fr/data#535]
Bonjour,

Je n'arrive pas a avoir le nombre de cas confirmés en utilisant le fichier chiffres-cles.json ou csv ?
Les données s'arretent fin mars ? Pas de soucis cependant pour les données déces/hospitalisees qui sont bien a jours
Savez vous ou je pourrais obtenir un fichier mis a jours des données de cas confirmés ?

**Comment by guillaumefe** [comment]
Hello! Le nombre de cas confirmés peut être consulté ici : https://github.com/opencovid19-fr/data/commit/166f81b81a8ba3b2b882aaeff41d15b03b75dea4

**Comment by guillaumefe** [comment]
Si cela peut-être utile, nous tenons également à jour une dépêche qui reprend quotidiennement le nombre de cas confirmés https://medium.com/@daily.digest.edition.du.soir ;)

**Comment by abdoulsn** [comment]
I close this issue, feel free to open it.

**Comment by j-bacal** [comment]
Il n'y aurait pas moyen de mettre a jour directement le fichier chiffres-cles.csv? 
Ca avait eu l'air de fonctionner au moins pendant un temps.
