### ISSUE TITLE
Suppression des données par département

### ISSUE THREAD

**Issue by jlvuattoux** [opencovid19-fr/data#537]
Les données départementales ont été supprimées (data-sources/sante-publique-france/covid_hospit.csv). Est-ce une erreur ou volontaire ?

**Comment by jdesboeufs** [comment]
Non elles sont désormais récupérées automatiquement à partir de cette page :
https://www.data.gouv.fr/fr/datasets/donnees-hospitalieres-relatives-a-lepidemie-de-covid-19/

**Comment by clotaire202** [comment]
J'ai effectivement trouvé cette nouvelle source depuis.
Merci beaucoup pour votre travail précieux pour qui, comme moi l'utiliser comme tableau de bord decisionnel en entreprise afin d'anticiper ce qu'on peut.
