### ISSUE TITLE
ARS PACA 2020-03-16

### ISSUE THREAD

**Issue by marion-paclot** [opencovid19-fr/data#54]
Indiquez que vous gérez cette date x ARS avant de vous lancer. Evite les multiples pull requests sur le même sujet. Merci

**Comment by racilk** [comment]
Il n'y a pas de données sur le point de situation du 16/03 mais uniquement des recommandations.

https://www.paca.ars.sante.fr/coronavirus-point-de-situation-du-16-mars-2020

**Comment by Binnette** [comment]
Ok, merci @racilk, on va attendre demain soir pour voir si un communiqué est édité

**Comment by alextuil** [comment]
nouveau communiqué dispo: https://www.paca.ars.sante.fr/coronavirus-en-provence-alpes-cote-dazur-point-de-situation-au-17-mars

**Comment by alextuil** [comment]
j'ouvre une autre issue pour créer le fichier YAML du 17 mars
