### ISSUE TITLE
From opencovid19 data to jhu data 

### ISSUE THREAD

**Issue by odadoun** [opencovid19-fr/data#543]
Hello,

first of all thanks for sharing your resources.
I am wondering which data from opencovid19 are used to update the JHU csv files 
https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series ?
By advance thank you
Cheers
Olivier
PS: I have a huge difference between deaths from SPF et JHU (maybe it is explain by the fact the ehpad's deaths are not taking into account)
![Capture d’écran 2020-09-22 à 11 53 49](https://user-images.githubusercontent.com/11535234/93869000-851c3380-fccb-11ea-995d-5f9ca140239c.jpg)

**Comment by abdoulsn** [comment]
This is two different  repo. no direct link. If i understand you question.

**Comment by odadoun** [comment]
Thanks Abdoulaye. I Asked JHU yesterday, they told me:
"Our data is sourced from https://dashboard.covid19.data.gouv.fr/vue-d-ensemble?location=FRA, which is the official France source" . I would like to know where I can get the information for "EHPAD et EMS", it should be opendata isn't it ? Basically from the French institutes informations (like SPF) I would like to retrieve the JHU total deaths.
Thank you
Bonne journée
Olivier
PS: I have started the thread in French if you think it is not needed we can continue in French :-)

**Comment by abdoulsn** [comment]
I see, our data are stored in `data/dist/*` or this [link](https://github.com/opencovid19-fr/data/tree/master/dist).

**Comment by odadoun** [comment]
Thanks. I have analysed the data.
It seems that there is no granularity for what concern the dead in the EHPAD. I mean only  the national values are  available (not by department nor regions), do you confirme that ?
There is a small difference between JHU and opencovid19 data ('deces EPAD'+'deces') 
![Capture d’écran 2020-09-23 à 18 53 27](https://user-images.githubusercontent.com/11535234/94044311-41f6b900-fdce-11ea-8072-97188da11f1d.jpg).
Do you have any idea where those difference is coming from ?
Thanks a lot for your patience
Olivier



.  Do you know where we can get information ?

**Comment by Dowser101** [comment]
Hello Olivier
The only clue i have on this is this article from 2nd half of May. I did not investigate further 
It states that some kind of mess was brought to light following the Spanish prime minister declarations controversy in May. He officially announced some results from JHU, claiming spain was on of the most advanced countries in terms of population testing campaigns, worldwide.

That numbers were proved wrong, and that lead to a kind of mea culpa from the John Hopkins side. 
They acknowledged the use of some Worldometer numbers to implement their own pandemic publications. Trouble is that Worldometer numbers collection was based on social media and implementation by volunteers. 
Of course they don’t publish any proprietary algorithm. 
But it is obvious that this leads to a curve that stands ahead of the real numbers, officially confirmed by french government.

Basically they have been suspected of a biased selection of the higher scores declared by contributors.
The fact that the curves begin to stick to each other after this polemic makes me think they just stop to do so after being forced to reckon this was not what readers expect from such an supposedly reliable organisation. 

https://edition.cnn.com/interactive/2020/05/world/worldometer-coronavirus-mystery/index.html
https://www.worldometers.info/coronavirus/

There could have been a "supplementary" twist as some results were published by SPF, and relayed on social media and online press many hours before the ministry of health official press communication. 
The story is related here :
https://www.francetvinfo.fr/sante/maladie/coronavirus/urgence-cafouillages-mille-feuille-d-indicateurs-dans-les-coulisses-des-donnees-tres-strategiques-sur-le-covid-19_4099757.html

Best regards

**Comment by odadoun** [comment]
Hello,

thanks to taking the time to answer me.
I think the problem is that JHU do not take into account Corse (perhaps the problem is from 1 digit + 1 letter?) + Dom-Tom (maybe the problem if from 3 digits?). 
If we compare (total deaths from SPF database in all France departments except Corse+DOM-TOM) + 
(total deaths in EHPAD from opencovid19 database in France, I guess it is for all departments)  to JHU
I rather have the same value  : 31181 vs 31103
![image](https://user-images.githubusercontent.com/11535234/94187583-6aeb7c80-fea8-11ea-991d-6e2bc455a32d.png)
From the plot we can observe a shift between the data (around 2 months)
This shift is also observed between deaths using SPF database and OpenCovid19 one.
![image](https://user-images.githubusercontent.com/11535234/94187684-9c644800-fea8-11ea-921f-8c43803f0a18.png)
Times shifting also observed for resuscitations
![Capture d’écran 2020-09-24 à 20 27 53](https://user-images.githubusercontent.com/11535234/94189353-e9491e00-feaa-11ea-8193-b4e967940e8c.jpg)
I have two questions:
- do you know why we have this time shifting ?
- is there a possibility to have department granularity for the deaths in EHPAD ?
By advance thank you
Olivier

**Comment by Dowser101** [comment]
As for your first question, I did not manage to decipher the colors right, sorry.
So...  JHU is the LOWER line, stupid me!
The worldometer problem that was pointed in May definitely did not apply to french figures. 
Then i don’t understand what is shown on your last posts. 
2 monts shift on deaths and réa? How come?
The peak day for the number of réa is the 8/04 with 6954. 
The 10 000 deaths threshold was passed on 07/04were 
Where did you get those peaks in February. I doubt this can be published by SPF or anywhere else... (please choose a definitive color for SPF and the other for opencovid, or i fear to become stupid again ;-) 
The national statistics of contamination and deaths in EHPAD have been proved inconsistent when it was made everyday, people "on the field" had no enough time to collect that numbers and i don’t even know the way it was compiled
But then it started to be accounted once a week, and it often resulted in NEGATIVE results.
I doubt anything valuable can be found for each departments in this conditions.

**Comment by Dowser101** [comment]
i could find some data sheet with the ehpad details, but you will have ton check further to know where the conceptor got the numbers !

**Comment by odadoun** [comment]
Ouf ! Sorry it was a bug in my code due to a bad python pandas concatenation.
So sfp and opencovid-19 are very closed 
hospitalises
<img width="567" alt="image" src="https://user-images.githubusercontent.com/11535234/94299672-47880680-ff68-11ea-9fbd-1d978fb5e7c3.png">
deces
<img width="474" alt="image" src="https://user-images.githubusercontent.com/11535234/94299871-8918b180-ff68-11ea-9e71-675725b30f4d.png">
Now I will check the link you sent me and continue my benchmark. Thanks a lot and have good week end 
cheers
Olivier

**Comment by Dowser101** [comment]
Contact the girl, it seems that she got it here but i don’t know where it could be hidden

**Comment by abdoulsn** [comment]
Feel free to open.
