### ISSUE TITLE
Bug / probleme de date

### ISSUE THREAD

**Issue by YoannParis** [opencovid19-fr/data#546]
Les chiffres du ministère de la Santé du jour (28/10/20) ont été publiés avec une mauvaise date (celle du 27/10/20). Le fichier du 2710 a été écrasé et du coup très forte hausse des indicateurs puisqu'ils s'agit de hausse sur 48h et non 24h !.

**Comment by jdesboeufs** [comment]
Ces données ont été corrigées dans la foulée. Une erreur de saisie a été propagée un peu partout.
