### ISSUE TITLE
Error in today's date format 2020-11_11 instead of 2020-11-11

### ISSUE THREAD

**Issue by eguidotti** [opencovid19-fr/data#549]
Hello and thanks for the repository!
I'd like to notify a small bug. The last line of the file
https://github.com/opencovid19-fr/data/blob/master/dist/chiffres-cles.csv
contains a wrong date format `2020-11_11` instead of `2020-11-11` (and it actually seems a wrong duplicate).
Thanks!

**Comment by jdesboeufs** [comment]
Fixed!
Thank you :)

**Comment by CleHou** [comment]
Bonjour, je retrouve le problème aujourd'hui sur la même date.
