### ISSUE TITLE
Missing data records for October 2020

### ISSUE THREAD

**Issue by gsagsa99** [opencovid19-fr/data#551]
Hello 

I downloaded the file today and for October , all records are missing  for "granularité = pays' AND  'source_nom= Ministère des Solidarités et de la Santé'

There were present still  on the 9th November !

Can those figures be restored ?

Thanks
Gsagsa99

**Comment by agardes** [comment]
I found an alternative for those datas : 

https://www.data.gouv.fr/fr/datasets/donnees-relatives-a-lepidemie-de-covid-19-en-france-vue-densemble/#_

**Comment by gsagsa99** [comment]
Many thanks

Le jeu. 12 nov. 2020 à 12:36, anne gardes <notifications@github.com> a
écrit :

**Comment by CleHou** [comment]
It would still be very much appreciated if it were possible to replace the missing data!

**Comment by gsagsa99** [comment]
Hi, 
the records are in today file .
Issue closed
gsa

**Comment by gsagsa99** [comment]
Closed
