### ISSUE TITLE
No updates since two days

### ISSUE THREAD

**Issue by gsagsa99** [opencovid19-fr/data#562]
Hello,

I am using the CSV file.  But since two days there seems to be no updates ?

Regards
gsagsa99

**Comment by VirusBlade** [comment]
Hello,
Yes there is a bug since 2021.
You can get the latest infos on my fork i found a fix https://github.com/VirusBlade/data/tree/master/dist
I created a pull request but i'm not the maintener #561.

**Comment by gsagsa99** [comment]
Hello

many thanks this helps a lot

regards
gsagsa99

Le dim. 3 janv. 2021 à 10:10, VirusBlade <notifications@github.com> a
écrit :

**Comment by jdesboeufs** [comment]
Fixed. Thx @VirusBlade and @gsagsa99
