### ISSUE TITLE
suggestion: fournir des données historisées

### ISSUE THREAD

**Issue by rndblnch** [opencovid19-fr/data#7]
bonjour,
merci pour ce travail.

juste un suggestion : vous pourriez constituer un fichier avec les séries temporelles comme par exemple ce que fait john hopkins :
https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series
ça permet de voir la dynamique au cours du temps en plus d'une image insantannée.

**Comment by jdesboeufs** [comment]
Bonjour,

Les fichiers sont justement historisées (colonne date).
Malheureusement nous n'allons pas encore très loin dans le passé, c'est pourquoi nous avons besoin de contributeurs.
Il est possible qu'on reprenne des données nationales de John Hopkins.

Peut-être que je n'ai pas compris votre question.

**Comment by atmoner** [comment]
Bonjours @jdesboeufs,
Je pense que @rndblnch parle d'un mode lecture qui permettrais de voir l’évolution en "live", avec un petit boutton lecture/stop, ce qui pourrais être une très bonne idée! 

Un exemple ici sur un line chart: https://webdeasy.de/en/programming-javascript-dynamic-live-chart/
  
![Dynamic-JavaScript-Chart](https://user-images.githubusercontent.com/1071490/76678532-1736d700-65d9-11ea-87d6-20e4681dfe8c.gif)

Je n'ai jamais fais d'affichage en live sur une map avec chart.js mais ce n'est surement pas impossible!

**Comment by jdesboeufs** [comment]
Bonjour @atmoner 

C'est n'est pas "animé", mais vous avez essayé le bouton pour changer la date des données ?
Quelqu'un sur Twitter a fait une vidéo.

**Comment by atmoner** [comment]
> Bonjour @atmoner
> 
> C'est n'est pas "animé", mais vous avez essayé le bouton pour changer la date des données ?
> Quelqu'un sur Twitter a fait une vidéo.

Oui j'ai vu cette partie là, peu être mettre une action ([ici](https://github.com/opencovid19-fr/dashboard/blob/cef812637b4dba65b3ab195cd6924a4bc94bcb5d/pages/index.js#L31)) qui demare l’animation à la date la plus ancienne.
J'ai bien essayé d'y ajouter un `setInterval()` mais sans succès :/ (je ne suis pas très à l'aise avec react)

J'ai attaquer un petit exemple d'ajout de data en live (random)
![openstreetmap](https://i.imgur.com/GRcG9Vb.gif)

Donc, question... J'ai le droit d'utiliser vos data librement?

**Comment by rndblnch** [comment]
ok, je n'avais pas vu la colonne date, merci.

**Comment by jdesboeufs** [comment]
@atmoner Toutes les données sont sous licence ouverte.
Le code est sous licence MIT.

Par contre cette question étant résolue, n'hésitez pas à ouvrir un issue spécifique pour parler de l'animation :)
