### ISSUE TITLE
Nouvelle-Calédonie : aucun cas recensé. On l'enregistre ?

### ISSUE THREAD

**Issue by ColinMaudry** [opencovid19-fr/data#78]
Communiqué de presse du 17 mars : https://gouv.nc/sites/default/files/atoms/files/2020.03.17_dp_nouvelles_mesures_du_gouvernement.pdf

**Comment by ColinMaudry** [comment]
Même si la Nouvelle-Calédonie n'a pas à proprement parler de "préfecture", je pense que le dossier `/prefectures/988` est adéquat pour d'éventuelles données.

**Comment by Xapitoun** [comment]
Ils ont une [Direction des Affaires Sanitaires et Sociales](https://dass.gouv.nc/), qui doit être l’équivalent des ARS. Le 20 mars, ils ont [2 cas](https://gouv.nc/info-coronavirus-covid-19/point-de-situation-sur-le-coronavirus-covid-19), il faut se tenir prêt à rajouter des données.

**Comment by ColinMaudry** [comment]
Auto-réponse : non.

**Comment by Xapitoun** [comment]
ajouté le dossier `/prefectures/988`
