### ISSUE TITLE
Polynésie française (éplucher les communiqués de presse)

### ISSUE THREAD

**Issue by ColinMaudry** [opencovid19-fr/data#79]
Les communiqués de presse des points de situation sont mélangés aux autres CP. Il faut donc parcourir la colonne de gauche. Une recherche (en haut à droite) peut peut-être aider.

http://www.polynesie-francaise.pref.gouv.fr/Actualites/Communiques-de-presse/2020/Coronavirus-Aucun-nouveau-cas-en-Polynesie-francaise

**Comment by racilk** [comment]
Je prends

**Comment by Xapitoun** [comment]
on crée un répertoire pour la polynésie française pour suivre les bulletins ?

**Comment by Xapitoun** [comment]
j’ai trouvé le site équivalent à l’ARS pour la [Polynésie Française](https://www.service-public.pf/dsp/),

**Comment by Xapitoun** [comment]
j’ai créé le dossier ARS et commencé à ajouter les fichiers

**Comment by JLPH987** [comment]
Un premier lot a été fait par @abdoulsn . Je m'occupe des dates manquantes (10/03 au 17/03) et d'ajouter la partie Haut Commissariat (equivalent préfecture).

http://www.polynesie-francaise.pref.gouv.fr/

**Comment by Binnette** [comment]
Hello pour vous coordonner, je vous conseille de discuter sur Slack:

https://join.slack.com/t/dataagainstcovid-19/shared_invite/zt-cgsplso2-LIvWeRHlf1ZFIrh~SPj~IA

**Comment by abdoulsn** [comment]
> Un premier lot a été fait par @abdoulsn . Je m'occupe des dates manquantes (10/03 au 17/03) et d'ajouter la partie Haut Commissariat (equivalent préfecture).
> 
> http://www.polynesie-francaise.pref.gouv.fr/

super, :)

**Comment by Binnette** [comment]
Tout est OK, je clos le ticket. Si besoin, vous pouvez le rouvrir :)
